package banner

type Sig struct {
	Pattern  string
	Service  string
	Version  string
	Category string
}

var Signatures = []Sig{

	{Pattern: `Server:\s*Apache/([\d.]+)`, Service: "Apache httpd", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Apache`, Service: "Apache httpd", Version: "", Category: "http"},
	{Pattern: `Server:\s*nginx/([\d.]+)`, Service: "nginx", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*nginx`, Service: "nginx", Version: "", Category: "http"},
	{Pattern: `Server:\s*Microsoft-IIS/([\d.]+)`, Service: "Microsoft IIS", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*lighttpd/([\d.]+)`, Service: "lighttpd", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*lighttpd`, Service: "lighttpd", Version: "", Category: "http"},
	{Pattern: `Server:\s*Apache-Coyote/([\d.]+)`, Service: "Apache Tomcat", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Apache Tomcat/([\d.]+)`, Service: "Apache Tomcat", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Tomcat`, Service: "Apache Tomcat", Version: "", Category: "http"},
	{Pattern: `Server:\s*Jetty/([\d.]+)`, Service: "Jetty", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Jetty`, Service: "Jetty", Version: "", Category: "http"},
	{Pattern: `Server:\s*GlassFish Server Open Source Edition\s*([\d.]+)`, Service: "GlassFish", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*GlassFish`, Service: "GlassFish", Version: "", Category: "http"},
	{Pattern: `Server:\s*WildFly/([\d.]+)`, Service: "WildFly", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*WildFly`, Service: "WildFly", Version: "", Category: "http"},
	{Pattern: `Server:\s*JBoss`, Service: "JBoss", Version: "", Category: "http"},
	{Pattern: `Server:\s*WebLogic ([\d.]+)`, Service: "WebLogic", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*WebLogic`, Service: "WebLogic", Version: "", Category: "http"},
	{Pattern: `Server:\s*IBM_HTTP_Server/([\d.]+)`, Service: "IBM WebSphere", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*WebSphere Application Server`, Service: "IBM WebSphere", Version: "", Category: "http"},
	{Pattern: `Server:\s*Caddy/([\d.]+)`, Service: "Caddy", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Caddy`, Service: "Caddy", Version: "", Category: "http"},
	{Pattern: `Server:\s*gunicorn/([\d.]+)`, Service: "Gunicorn", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*gunicorn`, Service: "Gunicorn", Version: "", Category: "http"},
	{Pattern: `Server:\s*uWSGI`, Service: "uWSGI", Version: "", Category: "http"},
	{Pattern: `Server:\s*Werkzeug/([\d.]+)`, Service: "Werkzeug", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Werkzeug`, Service: "Werkzeug", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Express`, Service: "Node.js Express", Version: "", Category: "http"},
	{Pattern: `Server:\s*Microsoft-HTTPAPI/([\d.]+)`, Service: "Microsoft HTTPAPI", Version: "extract", Category: "http"},
	{Pattern: `X-Powered-By:\s*ASP\.NET`, Service: "ASP.NET", Version: "", Category: "http"},
	{Pattern: `Server:\s*Kestrel`, Service: "Kestrel", Version: "", Category: "http"},
	{Pattern: `Server:\s*Cowboy`, Service: "Cowboy", Version: "", Category: "http"},
	{Pattern: `Server:\s*h2o/([\d.]+)`, Service: "h2o", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*h2o`, Service: "h2o", Version: "", Category: "http"},
	{Pattern: `Server:\s*openresty/([\d.]+)`, Service: "OpenResty", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*openresty`, Service: "OpenResty", Version: "", Category: "http"},
	{Pattern: `Server:\s*Tengine/([\d.]+)`, Service: "Tengine", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Tengine`, Service: "Tengine", Version: "", Category: "http"},
	{Pattern: `Server:\s*Hiawatha/([\d.]+)`, Service: "Hiawatha", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Cherokee/([\d.]+)`, Service: "Cherokee", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Resin/([\d.]+)`, Service: "Resin", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*CherryPy/([\d.]+)`, Service: "CherryPy", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*TornadoServer/([\d.]+)`, Service: "Tornado", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Python/Tornado`, Service: "Tornado", Version: "", Category: "http"},
	{Pattern: `Server:\s*aiohttp/([\d.]+)`, Service: "aiohttp", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*uvicorn`, Service: "Uvicorn", Version: "", Category: "http"},
	{Pattern: `Server:\s*hypercorn`, Service: "Hypercorn", Version: "", Category: "http"},
	{Pattern: `Server:\s*daphne`, Service: "Daphne", Version: "", Category: "http"},
	{Pattern: `Server:\s*waitress`, Service: "Waitress", Version: "", Category: "http"},
	{Pattern: `Server:\s*PasteWSGIServer`, Service: "Paste WSGI", Version: "", Category: "http"},
	{Pattern: `Server:\s*Pylons`, Service: "Pylons", Version: "", Category: "http"},
	{Pattern: `Server:\s*Pyramid`, Service: "Pyramid", Version: "", Category: "http"},
	{Pattern: `Server:\s*web2py/([\d.]+)`, Service: "web2py", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Bottle/([\d.]+)`, Service: "Bottle", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Falcon`, Service: "Falcon", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Sanic`, Service: "Sanic", Version: "", Category: "http"},
	{Pattern: `Server:\s*traefik`, Service: "Traefik", Version: "", Category: "http"},
	{Pattern: `Server:\s*envoy`, Service: "Envoy", Version: "", Category: "http"},
	{Pattern: `Server:\s*envoy-proxy`, Service: "Envoy Proxy", Version: "", Category: "http"},
	{Pattern: `Via:\s*[\d.]+ varnish`, Service: "Varnish", Version: "", Category: "http"},
	{Pattern: `X-Varnish:`, Service: "Varnish", Version: "", Category: "http"},
	{Pattern: `Server:\s*squid/([\d.]+)`, Service: "Squid", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*squid`, Service: "Squid", Version: "", Category: "http"},
	{Pattern: `Server:\s*BoaHTTP/([\d.]+)`, Service: "Boa HTTP", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*thttpd/([\d.]+)`, Service: "thttpd", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*mini_httpd/([\d.]+)`, Service: "mini_httpd", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*GoAhead-([\d.]+)`, Service: "GoAhead", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Monkey/([\d.]+)`, Service: "Monkey HTTP", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*civetweb/([\d.]+)`, Service: "Civetweb", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*mongoose`, Service: "Mongoose", Version: "", Category: "http"},
	{Pattern: `Server:\s*actix-web`, Service: "actix-web", Version: "", Category: "http"},
	{Pattern: `Server:\s*rocket`, Service: "Rocket", Version: "", Category: "http"},
	{Pattern: `Server:\s*warp`, Service: "Warp", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*PHP/([\d.]+)`, Service: "PHP", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*WEBrick/([\d.]+)`, Service: "WEBrick", Version: "extract", Category: "http"},
	{Pattern: `X-Powered-By:\s*Phusion Passenger ([\d.]+)`, Service: "Phusion Passenger", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Zeus/([\d.]+)`, Service: "Zeus Web Server", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Yaws/([\d.]+)`, Service: "Yaws", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*cpp-httplib/([\d.]+)`, Service: "cpp-httplib", Version: "extract", Category: "http"},
	{Pattern: `X-Powered-By:\s*Next\.js`, Service: "Next.js", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Nuxt`, Service: "Nuxt.js", Version: "", Category: "http"},
	{Pattern: `Server:\s*Roxen/([\d.]+)`, Service: "Roxen", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Pound`, Service: "Pound", Version: "", Category: "http"},
	{Pattern: `Server:\s*Pen/`, Service: "Pen", Version: "", Category: "http"},
	{Pattern: `Server:\s*HAProxy`, Service: "HAProxy", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*HAProxy`, Service: "HAProxy", Version: "", Category: "http"},
	{Pattern: `Server:\s*Nginx Plus`, Service: "Nginx Plus", Version: "", Category: "http"},

	{Pattern: `SSH-[\d.]+-OpenSSH_([\d.p]+)`, Service: "OpenSSH", Version: "extract", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-dropbear_([\d.]+)`, Service: "Dropbear SSH", Version: "extract", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-dropbear`, Service: "Dropbear SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-Cisco-[\d.]+`, Service: "Cisco SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-cisco`, Service: "Cisco SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-libssh_([\d.]+)`, Service: "libssh", Version: "extract", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-libssh2_([\d.]+)`, Service: "libssh2", Version: "extract", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-AsyncSSH_([\d.]+)`, Service: "AsyncSSH", Version: "extract", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-RomSShell_([\d.]+)`, Service: "RomSShell", Version: "extract", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-Bitvise-`, Service: "Bitvise SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-WinSSHD`, Service: "WinSSHD", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-CopSSH`, Service: "CopSSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-VShell_([\d.]+)`, Service: "VShell", Version: "extract", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-SSH_Tectia_([\d.]+)`, Service: "SSH Tectia", Version: "extract", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-F-Secure SSH`, Service: "F-Secure SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-Attachmate`, Service: "Attachmate SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-ERICSSON_`, Service: "Ericsson SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-FortiSSH`, Service: "Fortinet SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-JuniperSSH`, Service: "Juniper SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-Comware`, Service: "HPE Comware SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-MikroTik`, Service: "MikroTik SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-pfSense`, Service: "pfSense SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-OPNsense`, Service: "OPNsense SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-RouterOS`, Service: "RouterOS SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-Ubiquiti`, Service: "Ubiquiti SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-ArubaOS`, Service: "Aruba SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-Brocade`, Service: "Brocade SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-NetScaler`, Service: "NetScaler SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-BigIP`, Service: "BigIP SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-Sophos`, Service: "Sophos SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-WatchGuard`, Service: "WatchGuard SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-SonicWall`, Service: "SonicWall SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-ZyXEL`, Service: "Zyxel SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-DrayTek`, Service: "DrayTek SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-Lanner`, Service: "Lanner SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-HUAWEI`, Service: "Huawei SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-paramiko_([\d.]+)`, Service: "Paramiko SSH", Version: "extract", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-PaloAlto`, Service: "Palo Alto SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-JSCH`, Service: "JSch SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-lancom`, Service: "Lancom SSH", Version: "", Category: "ssh"},
	{Pattern: `SSH-[\d.]+-SecureCRT`, Service: "SecureCRT SSH", Version: "", Category: "ssh"},

	{Pattern: `220.*vsftpd ([\d.]+)`, Service: "vsftpd", Version: "extract", Category: "ftp"},
	{Pattern: `220.*vsftpd`, Service: "vsftpd", Version: "", Category: "ftp"},
	{Pattern: `220.*ProFTPD ([\d.]+)`, Service: "ProFTPD", Version: "extract", Category: "ftp"},
	{Pattern: `220.*ProFTPD`, Service: "ProFTPD", Version: "", Category: "ftp"},
	{Pattern: `220.*Pure-FTPd`, Service: "Pure-FTPd", Version: "", Category: "ftp"},
	{Pattern: `220.*wu-ftpd-([\d.]+)`, Service: "wu-ftpd", Version: "extract", Category: "ftp"},
	{Pattern: `220.*wu-ftpd`, Service: "wu-ftpd", Version: "", Category: "ftp"},
	{Pattern: `220.*FileZilla Server`, Service: "FileZilla FTP Server", Version: "", Category: "ftp"},
	{Pattern: `220.*Microsoft FTP Service`, Service: "Microsoft FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*IIS FTP`, Service: "IIS FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*Serv-U FTP Server ([\d.]+)`, Service: "Serv-U FTP", Version: "extract", Category: "ftp"},
	{Pattern: `220.*Serv-U`, Service: "Serv-U FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*Gene6 FTP Server`, Service: "Gene6 FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*Cerberus FTP Server`, Service: "Cerberus FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*Titan FTP Server`, Service: "Titan FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*CrushFTP`, Service: "CrushFTP", Version: "", Category: "ftp"},
	{Pattern: `220.*GlobalSCAPE EFT`, Service: "GlobalSCAPE EFT", Version: "", Category: "ftp"},
	{Pattern: `220.*bFTPd`, Service: "bFTPd", Version: "", Category: "ftp"},
	{Pattern: `220.*ncftpd`, Service: "ncftpd", Version: "", Category: "ftp"},
	{Pattern: `220.*GNU inetutils`, Service: "GNU inetutils FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*Tumbleweed`, Service: "Tumbleweed EMF", Version: "", Category: "ftp"},
	{Pattern: `220.*SunOS FTP`, Service: "Solaris FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*FreeBSD FTP`, Service: "FreeBSD FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*Ability Server`, Service: "Ability FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*BulletProof FTP`, Service: "BulletProof FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*WS_FTP`, Service: "WS_FTP Server", Version: "", Category: "ftp"},
	{Pattern: `220.*Cisco FTP`, Service: "Cisco FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*MikroTik`, Service: "MikroTik FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*3Com`, Service: "3Com FTP", Version: "", Category: "ftp"},
	{Pattern: `220.*AIX FTP`, Service: "AIX FTP", Version: "", Category: "ftp"},

	{Pattern: `220.*Postfix`, Service: "Postfix SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Sendmail ([\d./]+)`, Service: "Sendmail", Version: "extract", Category: "smtp"},
	{Pattern: `220.*Sendmail`, Service: "Sendmail", Version: "", Category: "smtp"},
	{Pattern: `220.*ESMTP Exim ([\d.]+)`, Service: "Exim SMTP", Version: "extract", Category: "smtp"},
	{Pattern: `220.*Exim`, Service: "Exim SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Microsoft ESMTP MAIL`, Service: "Microsoft Exchange SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Microsoft Exchange`, Service: "Microsoft Exchange SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*qmail`, Service: "qmail SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*ZMailer`, Service: "ZMailer SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*hMailServer`, Service: "hMailServer SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Lotus Domino`, Service: "Lotus Domino SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Lotus Notes`, Service: "Lotus Notes SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Novell GroupWise`, Service: "Novell GroupWise SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*IceWarp`, Service: "IceWarp SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*SmarterMail`, Service: "SmarterMail SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*CommuniGate Pro`, Service: "CommuniGate Pro SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*IMail`, Service: "IMail SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*MDaemon`, Service: "MDaemon SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Kerio Connect`, Service: "Kerio Connect SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*AXIGEN`, Service: "Axigen SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Xeams`, Service: "Xeams SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*MailEnable`, Service: "MailEnable SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Eudora Internet Mail`, Service: "Eudora SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Zimbra`, Service: "Zimbra SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Courier`, Service: "Courier SMTP", Version: "", Category: "smtp"},

	{Pattern: `([\d.]+)-MySQL`, Service: "MySQL", Version: "extract", Category: "database"},
	{Pattern: `([\d.]+)-MariaDB`, Service: "MariaDB", Version: "extract", Category: "database"},
	{Pattern: `mysql_native_password`, Service: "MySQL", Version: "", Category: "database"},
	{Pattern: `Percona Server`, Service: "Percona Server", Version: "", Category: "database"},
	{Pattern: `PostgreSQL ([\d.]+)`, Service: "PostgreSQL", Version: "extract", Category: "database"},
	{Pattern: `PostgreSQL`, Service: "PostgreSQL", Version: "", Category: "database"},
	{Pattern: `Microsoft SQL Server`, Service: "Microsoft SQL Server", Version: "", Category: "database"},
	{Pattern: `SQL Server 2019`, Service: "SQL Server 2019", Version: "", Category: "database"},
	{Pattern: `SQL Server 2017`, Service: "SQL Server 2017", Version: "", Category: "database"},
	{Pattern: `SQL Server 2016`, Service: "SQL Server 2016", Version: "", Category: "database"},
	{Pattern: `Oracle Database`, Service: "Oracle Database", Version: "", Category: "database"},
	{Pattern: `Oracle Corp`, Service: "Oracle Database", Version: "", Category: "database"},
	{Pattern: `CockroachDB`, Service: "CockroachDB", Version: "", Category: "database"},
	{Pattern: `cockroachdb`, Service: "CockroachDB", Version: "", Category: "database"},
	{Pattern: `TiDB`, Service: "TiDB", Version: "", Category: "database"},
	{Pattern: `tidb_server`, Service: "TiDB", Version: "", Category: "database"},
	{Pattern: `YugabyteDB`, Service: "YugabyteDB", Version: "", Category: "database"},
	{Pattern: `yugabyte`, Service: "YugabyteDB", Version: "", Category: "database"},
	{Pattern: `PlanetScale`, Service: "PlanetScale", Version: "", Category: "database"},
	{Pattern: `MongoDB ([\d.]+)`, Service: "MongoDB", Version: "extract", Category: "database"},
	{Pattern: `MongoDB`, Service: "MongoDB", Version: "", Category: "database"},
	{Pattern: `redis_version:([\d.]+)`, Service: "Redis", Version: "extract", Category: "database"},
	{Pattern: `Redis server v=([\d.]+)`, Service: "Redis", Version: "extract", Category: "database"},
	{Pattern: `Redis`, Service: "Redis", Version: "", Category: "database"},
	{Pattern: `VERSION ([\d.]+)`, Service: "Memcached", Version: "extract", Category: "database"},
	{Pattern: `Memcached ([\d.]+)`, Service: "Memcached", Version: "extract", Category: "database"},
	{Pattern: `Cassandra database`, Service: "Cassandra", Version: "", Category: "database"},
	{Pattern: `CQL_VERSION`, Service: "Cassandra", Version: "", Category: "database"},
	{Pattern: `"tagline":\s*"You Know, for Search"`, Service: "Elasticsearch", Version: "", Category: "database"},
	{Pattern: `"tagline":"You Know, for Search"`, Service: "Elasticsearch", Version: "", Category: "database"},
	{Pattern: `"number":\s*"([\d.]+)"`, Service: "Elasticsearch", Version: "extract", Category: "database"},
	{Pattern: `OpenSearch`, Service: "OpenSearch", Version: "", Category: "database"},
	{Pattern: `InfluxDB v([\d.]+)`, Service: "InfluxDB", Version: "extract", Category: "database"},
	{Pattern: `InfluxDB`, Service: "InfluxDB", Version: "", Category: "database"},
	{Pattern: `"neo4j"`, Service: "Neo4j", Version: "", Category: "database"},
	{Pattern: `Neo4j`, Service: "Neo4j", Version: "", Category: "database"},
	{Pattern: `"couchdb":\s*"Welcome"`, Service: "CouchDB", Version: "", Category: "database"},
	{Pattern: `RethinkDB`, Service: "RethinkDB", Version: "", Category: "database"},
	{Pattern: `ArangoDB`, Service: "ArangoDB", Version: "", Category: "database"},
	{Pattern: `Couchbase Server`, Service: "Couchbase", Version: "", Category: "database"},
	{Pattern: `HBase`, Service: "HBase", Version: "", Category: "database"},
	{Pattern: `ScyllaDB`, Service: "ScyllaDB", Version: "", Category: "database"},
	{Pattern: `VoltDB`, Service: "VoltDB", Version: "", Category: "database"},
	{Pattern: `NuoDB`, Service: "NuoDB", Version: "", Category: "database"},
	{Pattern: `Apache Druid`, Service: "Druid", Version: "", Category: "database"},
	{Pattern: `ClickHouse`, Service: "ClickHouse", Version: "", Category: "database"},
	{Pattern: `DuckDB`, Service: "DuckDB", Version: "", Category: "database"},
	{Pattern: `QuestDB`, Service: "QuestDB", Version: "", Category: "database"},
	{Pattern: `TimescaleDB`, Service: "TimescaleDB", Version: "", Category: "database"},
	{Pattern: `VictoriaMetrics`, Service: "VictoriaMetrics", Version: "", Category: "database"},
	{Pattern: `Dgraph`, Service: "Dgraph", Version: "", Category: "database"},
	{Pattern: `JanusGraph`, Service: "JanusGraph", Version: "", Category: "database"},
	{Pattern: `DynamoDB Local`, Service: "DynamoDB Local", Version: "", Category: "database"},
	{Pattern: `faunadb`, Service: "FaunaDB", Version: "", Category: "database"},
	{Pattern: `Zookeeper version: ([\d.]+)`, Service: "ZooKeeper", Version: "extract", Category: "database"},
	{Pattern: `ZooKeeper`, Service: "ZooKeeper", Version: "", Category: "database"},
	{Pattern: `prometheus_tsdb`, Service: "Prometheus TSDB", Version: "", Category: "database"},
	{Pattern: `OrientDB`, Service: "OrientDB", Version: "", Category: "database"},
	{Pattern: `innodb`, Service: "MySQL/InnoDB", Version: "", Category: "database"},
	{Pattern: `mariadb`, Service: "MariaDB", Version: "", Category: "database"},

	{Pattern: `RabbitMQ ([\d.]+)`, Service: "RabbitMQ", Version: "extract", Category: "mq"},
	{Pattern: `RabbitMQ`, Service: "RabbitMQ", Version: "", Category: "mq"},
	{Pattern: `ActiveMQ ([\d.]+)`, Service: "ActiveMQ", Version: "extract", Category: "mq"},
	{Pattern: `ActiveMQ`, Service: "ActiveMQ", Version: "", Category: "mq"},
	{Pattern: `Apache Kafka`, Service: "Apache Kafka", Version: "", Category: "mq"},
	{Pattern: `kafka`, Service: "Kafka", Version: "", Category: "mq"},
	{Pattern: `NATS Server v([\d.]+)`, Service: "NATS Server", Version: "extract", Category: "mq"},
	{Pattern: `"server_id"`, Service: "NATS Server", Version: "", Category: "mq"},
	{Pattern: `Apache Pulsar`, Service: "Apache Pulsar", Version: "", Category: "mq"},
	{Pattern: `mosquitto version ([\d.]+)`, Service: "Mosquitto MQTT", Version: "extract", Category: "mq"},
	{Pattern: `mosquitto`, Service: "Mosquitto MQTT", Version: "", Category: "mq"},
	{Pattern: `EMQ X`, Service: "EMQx", Version: "", Category: "mq"},
	{Pattern: `emqx`, Service: "EMQx", Version: "", Category: "mq"},
	{Pattern: `HiveMQ`, Service: "HiveMQ", Version: "", Category: "mq"},
	{Pattern: `VerneMQ`, Service: "VerneMQ", Version: "", Category: "mq"},
	{Pattern: `Solace`, Service: "Solace PubSub", Version: "", Category: "mq"},
	{Pattern: `IBM MQ`, Service: "IBM MQ", Version: "", Category: "mq"},
	{Pattern: `WebSphere MQ`, Service: "IBM WebSphere MQ", Version: "", Category: "mq"},
	{Pattern: `ZeroMQ`, Service: "ZeroMQ", Version: "", Category: "mq"},
	{Pattern: `nanomq`, Service: "NanoMQ", Version: "", Category: "mq"},
	{Pattern: `RocketMQ`, Service: "RocketMQ", Version: "", Category: "mq"},
	{Pattern: `NSQ`, Service: "NSQ", Version: "", Category: "mq"},
	{Pattern: `beanstalkd`, Service: "Beanstalkd", Version: "", Category: "mq"},
	{Pattern: `USING beanstalkd`, Service: "Beanstalkd", Version: "", Category: "mq"},
	{Pattern: `Faktory`, Service: "Faktory", Version: "", Category: "mq"},
	{Pattern: `Temporal`, Service: "Temporal", Version: "", Category: "mq"},
	{Pattern: `IronMQ`, Service: "IronMQ", Version: "", Category: "mq"},
	{Pattern: `Redisson`, Service: "Redisson", Version: "", Category: "mq"},
	{Pattern: `sidekiq`, Service: "Sidekiq", Version: "", Category: "mq"},
	{Pattern: `MQTT broker`, Service: "MQTT Broker", Version: "", Category: "mq"},

	{Pattern: `RFB 003\.`, Service: "VNC", Version: "", Category: "remote"},
	{Pattern: `RFB 004\.`, Service: "VNC", Version: "", Category: "remote"},
	{Pattern: `RFB 005\.`, Service: "VNC", Version: "", Category: "remote"},
	{Pattern: `RFB ([\d.]+)`, Service: "VNC", Version: "extract", Category: "remote"},
	{Pattern: `UltraVNC`, Service: "UltraVNC", Version: "", Category: "remote"},
	{Pattern: `TigerVNC`, Service: "TigerVNC", Version: "", Category: "remote"},
	{Pattern: `x11vnc`, Service: "x11vnc", Version: "", Category: "remote"},
	{Pattern: `RealVNC`, Service: "RealVNC", Version: "", Category: "remote"},
	{Pattern: `LibVNCServer`, Service: "LibVNCServer", Version: "", Category: "remote"},
	{Pattern: `TightVNC`, Service: "TightVNC", Version: "", Category: "remote"},
	{Pattern: `Vine Server`, Service: "Vine Server", Version: "", Category: "remote"},
	{Pattern: `Apple Remote Desktop`, Service: "Apple Remote Desktop", Version: "", Category: "remote"},
	{Pattern: `xrdp`, Service: "xrdp", Version: "", Category: "remote"},
	{Pattern: `FreeRDP`, Service: "FreeRDP", Version: "", Category: "remote"},
	{Pattern: `RDP \(Microsoft Terminal`, Service: "Microsoft RDP", Version: "", Category: "remote"},
	{Pattern: `NX NoMachine`, Service: "NoMachine NX", Version: "", Category: "remote"},
	{Pattern: `NoMachine`, Service: "NoMachine NX", Version: "", Category: "remote"},
	{Pattern: `Citrix ICA`, Service: "Citrix ICA", Version: "", Category: "remote"},
	{Pattern: `Citrix XenApp`, Service: "Citrix XenApp", Version: "", Category: "remote"},
	{Pattern: `Citrix Receiver`, Service: "Citrix Receiver", Version: "", Category: "remote"},
	{Pattern: `VMware Horizon`, Service: "VMware Horizon", Version: "", Category: "remote"},
	{Pattern: `TeamViewer`, Service: "TeamViewer", Version: "", Category: "remote"},
	{Pattern: `AnyDesk`, Service: "AnyDesk", Version: "", Category: "remote"},
	{Pattern: `Splashtop`, Service: "Splashtop", Version: "", Category: "remote"},
	{Pattern: `LogMeIn`, Service: "LogMeIn", Version: "", Category: "remote"},
	{Pattern: `Chrome Remote Desktop`, Service: "Chrome Remote Desktop", Version: "", Category: "remote"},

	{Pattern: `Cisco IOS Software`, Service: "Cisco IOS", Version: "", Category: "network"},
	{Pattern: `Cisco Internetwork Operating System`, Service: "Cisco IOS", Version: "", Category: "network"},
	{Pattern: `IOS-XE`, Service: "Cisco IOS-XE", Version: "", Category: "network"},
	{Pattern: `NX-OS`, Service: "Cisco NX-OS", Version: "", Category: "network"},
	{Pattern: `Cisco Adaptive Security`, Service: "Cisco ASA", Version: "", Category: "network"},
	{Pattern: `Cisco Meraki`, Service: "Cisco Meraki", Version: "", Category: "network"},
	{Pattern: `Juniper Networks`, Service: "Juniper Networks", Version: "", Category: "network"},
	{Pattern: `JUNOS ([\d.]+)`, Service: "Juniper JUNOS", Version: "extract", Category: "network"},
	{Pattern: `JUNOS`, Service: "Juniper JUNOS", Version: "", Category: "network"},
	{Pattern: `MikroTik RouterOS ([\d.]+)`, Service: "MikroTik RouterOS", Version: "extract", Category: "network"},
	{Pattern: `MikroTik`, Service: "MikroTik", Version: "", Category: "network"},
	{Pattern: `RouterOS`, Service: "RouterOS", Version: "", Category: "network"},
	{Pattern: `EdgeOS`, Service: "Ubiquiti EdgeOS", Version: "", Category: "network"},
	{Pattern: `UniFiOS`, Service: "Ubiquiti UniFiOS", Version: "", Category: "network"},
	{Pattern: `Aruba`, Service: "Aruba Networks", Version: "", Category: "network"},
	{Pattern: `HP Comware`, Service: "HPE Comware", Version: "", Category: "network"},
	{Pattern: `Arista Networks`, Service: "Arista EOS", Version: "", Category: "network"},
	{Pattern: `Arista EOS`, Service: "Arista EOS", Version: "", Category: "network"},
	{Pattern: `Cumulus Linux`, Service: "Cumulus Linux", Version: "", Category: "network"},
	{Pattern: `SONiC`, Service: "SONiC", Version: "", Category: "network"},
	{Pattern: `OpenWrt`, Service: "OpenWRT", Version: "", Category: "network"},
	{Pattern: `DD-WRT`, Service: "DD-WRT", Version: "", Category: "network"},
	{Pattern: `Tomato`, Service: "Tomato firmware", Version: "", Category: "network"},
	{Pattern: `pfSense`, Service: "pfSense", Version: "", Category: "network"},
	{Pattern: `OPNsense`, Service: "OPNsense", Version: "", Category: "network"},
	{Pattern: `Sophos`, Service: "Sophos", Version: "", Category: "network"},
	{Pattern: `FortiOS`, Service: "Fortinet FortiOS", Version: "", Category: "network"},
	{Pattern: `PAN-OS`, Service: "Palo Alto PAN-OS", Version: "", Category: "network"},
	{Pattern: `Check Point Gaia`, Service: "Check Point GAIA", Version: "", Category: "network"},
	{Pattern: `Fireware`, Service: "WatchGuard Fireware", Version: "", Category: "network"},
	{Pattern: `SonicOS`, Service: "SonicWall SonicOS", Version: "", Category: "network"},
	{Pattern: `ZyNOS`, Service: "Zyxel ZyNOS", Version: "", Category: "network"},
	{Pattern: `DrayTek`, Service: "DrayTek", Version: "", Category: "network"},
	{Pattern: `NETGEAR ProSafe`, Service: "Netgear ProSafe", Version: "", Category: "network"},
	{Pattern: `D-Link`, Service: "D-Link", Version: "", Category: "network"},
	{Pattern: `TP-Link`, Service: "TP-Link", Version: "", Category: "network"},
	{Pattern: `Linksys`, Service: "Linksys", Version: "", Category: "network"},
	{Pattern: `Brocade`, Service: "Brocade", Version: "", Category: "network"},
	{Pattern: `Extreme Networks`, Service: "Extreme Networks", Version: "", Category: "network"},
	{Pattern: `Ruckus`, Service: "Ruckus", Version: "", Category: "network"},
	{Pattern: `ADTRAN`, Service: "ADTRAN", Version: "", Category: "network"},
	{Pattern: `Calix`, Service: "Calix", Version: "", Category: "network"},
	{Pattern: `Cambium`, Service: "Cambium Networks", Version: "", Category: "network"},
	{Pattern: `Cradlepoint`, Service: "Cradlepoint", Version: "", Category: "network"},

	{Pattern: `Metasploit`, Service: "Metasploit", Version: "", Category: "security"},
	{Pattern: `meterpreter`, Service: "Metasploit Meterpreter", Version: "", Category: "security"},
	{Pattern: `Cobalt Strike`, Service: "Cobalt Strike C2", Version: "", Category: "security"},
	{Pattern: `teamserver`, Service: "Cobalt Strike C2", Version: "", Category: "security"},
	{Pattern: `Covenant`, Service: "Covenant C2", Version: "", Category: "security"},
	{Pattern: `Sliver`, Service: "Sliver C2", Version: "", Category: "security"},
	{Pattern: `Havoc C2`, Service: "Havoc C2", Version: "", Category: "security"},
	{Pattern: `Brute Ratel`, Service: "Brute Ratel C4", Version: "", Category: "security"},
	{Pattern: `PowerShell Empire`, Service: "PowerShell Empire", Version: "", Category: "security"},
	{Pattern: `Mythic C2`, Service: "Mythic C2", Version: "", Category: "security"},
	{Pattern: `Nighthawk`, Service: "Nighthawk C2", Version: "", Category: "security"},
	{Pattern: `acme-challenge`, Service: "ACME Challenge Server", Version: "", Category: "security"},
	{Pattern: `OpenVAS`, Service: "OpenVAS", Version: "", Category: "security"},
	{Pattern: `Nessus`, Service: "Nessus", Version: "", Category: "security"},
	{Pattern: `Qualys`, Service: "Qualys", Version: "", Category: "security"},
	{Pattern: `Nexpose`, Service: "Rapid7 Nexpose", Version: "", Category: "security"},
	{Pattern: `tenable`, Service: "Tenable", Version: "", Category: "security"},
	{Pattern: `Greenbone`, Service: "Greenbone Security", Version: "", Category: "security"},
	{Pattern: `Nikto`, Service: "Nikto", Version: "", Category: "security"},
	{Pattern: `sqlmap`, Service: "SQLmap", Version: "", Category: "security"},
	{Pattern: `w3af`, Service: "w3af", Version: "", Category: "security"},
	{Pattern: `OWASP ZAP`, Service: "OWASP ZAP", Version: "", Category: "security"},
	{Pattern: `nuclei`, Service: "Nuclei", Version: "", Category: "security"},
	{Pattern: `Burp Suite`, Service: "Burp Suite", Version: "", Category: "security"},
	{Pattern: `HostedScan`, Service: "HostedScan", Version: "", Category: "security"},

	{Pattern: `Grafana v([\d.]+)`, Service: "Grafana", Version: "extract", Category: "monitoring"},
	{Pattern: `Grafana`, Service: "Grafana", Version: "", Category: "monitoring"},
	{Pattern: `Prometheus/([\d.]+)`, Service: "Prometheus", Version: "extract", Category: "monitoring"},
	{Pattern: `Prometheus`, Service: "Prometheus", Version: "", Category: "monitoring"},
	{Pattern: `Alertmanager`, Service: "Prometheus AlertManager", Version: "", Category: "monitoring"},
	{Pattern: `Nagios Core`, Service: "Nagios", Version: "", Category: "monitoring"},
	{Pattern: `Nagios XI`, Service: "Nagios XI", Version: "", Category: "monitoring"},
	{Pattern: `Nagios`, Service: "Nagios", Version: "", Category: "monitoring"},
	{Pattern: `Zabbix`, Service: "Zabbix", Version: "", Category: "monitoring"},
	{Pattern: `Datadog Agent`, Service: "Datadog Agent", Version: "", Category: "monitoring"},
	{Pattern: `newrelic`, Service: "New Relic Agent", Version: "", Category: "monitoring"},
	{Pattern: `Dynatrace`, Service: "Dynatrace OneAgent", Version: "", Category: "monitoring"},
	{Pattern: `AppDynamics`, Service: "AppDynamics", Version: "", Category: "monitoring"},
	{Pattern: `Splunk`, Service: "Splunk", Version: "", Category: "monitoring"},
	{Pattern: `Graylog`, Service: "Graylog", Version: "", Category: "monitoring"},
	{Pattern: `Logstash`, Service: "Logstash", Version: "", Category: "monitoring"},
	{Pattern: `Kibana`, Service: "Kibana", Version: "", Category: "monitoring"},
	{Pattern: `Fluentd`, Service: "Fluentd", Version: "", Category: "monitoring"},
	{Pattern: `Loki`, Service: "Loki", Version: "", Category: "monitoring"},
	{Pattern: `Jaeger`, Service: "Jaeger", Version: "", Category: "monitoring"},
	{Pattern: `Zipkin`, Service: "Zipkin", Version: "", Category: "monitoring"},
	{Pattern: `OpenTelemetry`, Service: "OpenTelemetry Collector", Version: "", Category: "monitoring"},
	{Pattern: `cAdvisor`, Service: "cAdvisor", Version: "", Category: "monitoring"},
	{Pattern: `netdata`, Service: "Netdata", Version: "", Category: "monitoring"},
	{Pattern: `Cacti`, Service: "Cacti", Version: "", Category: "monitoring"},
	{Pattern: `Observium`, Service: "Observium", Version: "", Category: "monitoring"},
	{Pattern: `LibreNMS`, Service: "LibreNMS", Version: "", Category: "monitoring"},
	{Pattern: `# HELP go_goroutines`, Service: "Prometheus metrics", Version: "", Category: "monitoring"},
	{Pattern: `victoria_metrics_version`, Service: "VictoriaMetrics", Version: "", Category: "monitoring"},
	{Pattern: `tempo`, Service: "Grafana Tempo", Version: "", Category: "monitoring"},

	{Pattern: `"ServerVersion"`, Service: "Docker API", Version: "", Category: "container"},
	{Pattern: `Docker-Distribution-Api-Version`, Service: "Docker Registry", Version: "", Category: "container"},
	{Pattern: `docker`, Service: "Docker", Version: "", Category: "container"},
	{Pattern: `containerd`, Service: "containerd", Version: "", Category: "container"},
	{Pattern: `Kubernetes`, Service: "Kubernetes", Version: "", Category: "container"},
	{Pattern: `k3s`, Service: "k3s", Version: "", Category: "container"},
	{Pattern: `k0s`, Service: "k0s", Version: "", Category: "container"},
	{Pattern: `OpenShift`, Service: "OpenShift", Version: "", Category: "container"},
	{Pattern: `Rancher`, Service: "Rancher", Version: "", Category: "container"},
	{Pattern: `Portainer`, Service: "Portainer", Version: "", Category: "container"},
	{Pattern: `Consul`, Service: "Consul", Version: "", Category: "container"},
	{Pattern: `X-Vault-Request`, Service: "HashiCorp Vault", Version: "", Category: "container"},
	{Pattern: `Vault`, Service: "HashiCorp Vault", Version: "", Category: "container"},
	{Pattern: `Nomad`, Service: "HashiCorp Nomad", Version: "", Category: "container"},
	{Pattern: `Terraform Enterprise`, Service: "Terraform Enterprise", Version: "", Category: "container"},
	{Pattern: `Amazon ECS`, Service: "AWS ECS", Version: "", Category: "container"},
	{Pattern: `Knative`, Service: "Knative", Version: "", Category: "container"},
	{Pattern: `ArgoCD`, Service: "Argo CD", Version: "", Category: "container"},
	{Pattern: `Argo CD`, Service: "Argo CD", Version: "", Category: "container"},
	{Pattern: `FluxCD`, Service: "Flux CD", Version: "", Category: "container"},
	{Pattern: `cert-manager`, Service: "cert-manager", Version: "", Category: "container"},
	{Pattern: `Istio`, Service: "Istio", Version: "", Category: "container"},
	{Pattern: `Linkerd`, Service: "Linkerd", Version: "", Category: "container"},
	{Pattern: `Harbor`, Service: "Harbor Registry", Version: "", Category: "container"},
	{Pattern: `Spinnaker`, Service: "Spinnaker", Version: "", Category: "container"},

	{Pattern: `Jenkins/([\d.]+)`, Service: "Jenkins", Version: "extract", Category: "cicd"},
	{Pattern: `Jenkins`, Service: "Jenkins", Version: "", Category: "cicd"},
	{Pattern: `X-Gitlab-Meta`, Service: "GitLab", Version: "", Category: "cicd"},
	{Pattern: `Gitlab`, Service: "GitLab", Version: "", Category: "cicd"},
	{Pattern: `GitHub Actions`, Service: "GitHub Actions", Version: "", Category: "cicd"},
	{Pattern: `Drone`, Service: "Drone CI", Version: "", Category: "cicd"},
	{Pattern: `CircleCI`, Service: "CircleCI", Version: "", Category: "cicd"},
	{Pattern: `Travis CI`, Service: "Travis CI", Version: "", Category: "cicd"},
	{Pattern: `TeamCity`, Service: "TeamCity", Version: "", Category: "cicd"},
	{Pattern: `Bamboo`, Service: "Atlassian Bamboo", Version: "", Category: "cicd"},
	{Pattern: `Azure DevOps`, Service: "Azure DevOps", Version: "", Category: "cicd"},
	{Pattern: `Octopus Deploy`, Service: "Octopus Deploy", Version: "", Category: "cicd"},
	{Pattern: `GoCD`, Service: "GoCD", Version: "", Category: "cicd"},
	{Pattern: `Tekton`, Service: "Tekton", Version: "", Category: "cicd"},
	{Pattern: `Woodpecker`, Service: "Woodpecker CI", Version: "", Category: "cicd"},
	{Pattern: `Forgejo`, Service: "Forgejo", Version: "", Category: "cicd"},
	{Pattern: `Gitea`, Service: "Gitea", Version: "", Category: "cicd"},
	{Pattern: `Nexus Repository`, Service: "Nexus Repository", Version: "", Category: "cicd"},
	{Pattern: `JFrog Artifactory`, Service: "JFrog Artifactory", Version: "", Category: "cicd"},
	{Pattern: `Concourse`, Service: "Concourse CI", Version: "", Category: "cicd"},

	{Pattern: `WordPress/([\d.]+)`, Service: "WordPress", Version: "extract", Category: "webapp"},
	{Pattern: `wp-content`, Service: "WordPress", Version: "", Category: "webapp"},
	{Pattern: `WordPress`, Service: "WordPress", Version: "", Category: "webapp"},
	{Pattern: `Joomla`, Service: "Joomla", Version: "", Category: "webapp"},
	{Pattern: `X-Generator:\s*Drupal ([\d]+)`, Service: "Drupal", Version: "extract", Category: "webapp"},
	{Pattern: `Drupal`, Service: "Drupal", Version: "", Category: "webapp"},
	{Pattern: `Magento`, Service: "Magento", Version: "", Category: "webapp"},
	{Pattern: `WooCommerce`, Service: "WooCommerce", Version: "", Category: "webapp"},
	{Pattern: `PrestaShop`, Service: "PrestaShop", Version: "", Category: "webapp"},
	{Pattern: `OpenCart`, Service: "OpenCart", Version: "", Category: "webapp"},
	{Pattern: `TYPO3`, Service: "TYPO3", Version: "", Category: "webapp"},
	{Pattern: `Contao`, Service: "Contao CMS", Version: "", Category: "webapp"},
	{Pattern: `Plone`, Service: "Plone CMS", Version: "", Category: "webapp"},
	{Pattern: `concrete5`, Service: "Concrete5", Version: "", Category: "webapp"},
	{Pattern: `Ghost`, Service: "Ghost CMS", Version: "", Category: "webapp"},
	{Pattern: `Grav`, Service: "Grav CMS", Version: "", Category: "webapp"},
	{Pattern: `October CMS`, Service: "October CMS", Version: "", Category: "webapp"},
	{Pattern: `CraftCMS`, Service: "Craft CMS", Version: "", Category: "webapp"},
	{Pattern: `Craft CMS`, Service: "Craft CMS", Version: "", Category: "webapp"},
	{Pattern: `Kirby`, Service: "Kirby CMS", Version: "", Category: "webapp"},
	{Pattern: `Statamic`, Service: "Statamic", Version: "", Category: "webapp"},
	{Pattern: `Hugo`, Service: "Hugo", Version: "", Category: "webapp"},
	{Pattern: `Jekyll`, Service: "Jekyll", Version: "", Category: "webapp"},
	{Pattern: `Gatsby`, Service: "Gatsby", Version: "", Category: "webapp"},
	{Pattern: `Next\.js`, Service: "Next.js", Version: "", Category: "webapp"},
	{Pattern: `Nuxt`, Service: "Nuxt.js", Version: "", Category: "webapp"},
	{Pattern: `Strapi`, Service: "Strapi", Version: "", Category: "webapp"},
	{Pattern: `Directus`, Service: "Directus", Version: "", Category: "webapp"},
	{Pattern: `Wagtail`, Service: "Wagtail CMS", Version: "", Category: "webapp"},
	{Pattern: `Umbraco`, Service: "Umbraco", Version: "", Category: "webapp"},
	{Pattern: `Sitecore`, Service: "Sitecore", Version: "", Category: "webapp"},
	{Pattern: `Adobe Experience Manager`, Service: "Adobe AEM", Version: "", Category: "webapp"},
	{Pattern: `Shopify`, Service: "Shopify", Version: "", Category: "webapp"},
	{Pattern: `Squarespace`, Service: "Squarespace", Version: "", Category: "webapp"},
	{Pattern: `SvelteKit`, Service: "SvelteKit", Version: "", Category: "webapp"},
	{Pattern: `Remix`, Service: "Remix", Version: "", Category: "webapp"},
	{Pattern: `Astro`, Service: "Astro", Version: "", Category: "webapp"},
	{Pattern: `Wix`, Service: "Wix", Version: "", Category: "webapp"},
	{Pattern: `KeystoneJS`, Service: "KeystoneJS", Version: "", Category: "webapp"},
	{Pattern: `Sanity`, Service: "Sanity", Version: "", Category: "webapp"},

	{Pattern: `Roundcube`, Service: "Roundcube", Version: "", Category: "mail"},
	{Pattern: `Zimbra`, Service: "Zimbra", Version: "", Category: "mail"},
	{Pattern: `Outlook Web App`, Service: "Microsoft Exchange OWA", Version: "", Category: "mail"},
	{Pattern: `Exchange OWA`, Service: "Microsoft Exchange OWA", Version: "", Category: "mail"},
	{Pattern: `Horde`, Service: "Horde Webmail", Version: "", Category: "mail"},
	{Pattern: `SquirrelMail`, Service: "SquirrelMail", Version: "", Category: "mail"},
	{Pattern: `RainLoop`, Service: "RainLoop Webmail", Version: "", Category: "mail"},
	{Pattern: `AfterLogic`, Service: "AfterLogic WebMail", Version: "", Category: "mail"},
	{Pattern: `OX App Suite`, Service: "Open-Xchange App Suite", Version: "", Category: "mail"},
	{Pattern: `Open-Xchange`, Service: "Open-Xchange", Version: "", Category: "mail"},
	{Pattern: `Zarafa`, Service: "Zarafa", Version: "", Category: "mail"},
	{Pattern: `Kopano`, Service: "Kopano", Version: "", Category: "mail"},
	{Pattern: `Kerio Connect`, Service: "Kerio Connect", Version: "", Category: "mail"},
	{Pattern: `Postfix Admin`, Service: "Postfix Admin", Version: "", Category: "mail"},
	{Pattern: `Mail-in-a-Box`, Service: "Mail-in-a-Box", Version: "", Category: "mail"},
	{Pattern: `iRedMail`, Service: "iRedMail", Version: "", Category: "mail"},
	{Pattern: `Modoboa`, Service: "Modoboa", Version: "", Category: "mail"},
	{Pattern: `Mailu`, Service: "Mailu", Version: "", Category: "mail"},
	{Pattern: `Dovecot`, Service: "Dovecot IMAP", Version: "", Category: "mail"},
	{Pattern: `Cyrus IMAP`, Service: "Cyrus IMAP", Version: "", Category: "mail"},
	{Pattern: `Courier IMAP`, Service: "Courier IMAP", Version: "", Category: "mail"},
	{Pattern: `UW-IMAP`, Service: "UW-IMAP", Version: "", Category: "mail"},

	{Pattern: `auth/realms`, Service: "Keycloak", Version: "", Category: "auth"},
	{Pattern: `Keycloak`, Service: "Keycloak", Version: "", Category: "auth"},
	{Pattern: `Okta`, Service: "Okta", Version: "", Category: "auth"},
	{Pattern: `Auth0`, Service: "Auth0", Version: "", Category: "auth"},
	{Pattern: `Authelia`, Service: "Authelia", Version: "", Category: "auth"},
	{Pattern: `authentik`, Service: "Authentik", Version: "", Category: "auth"},
	{Pattern: `Casdoor`, Service: "Casdoor", Version: "", Category: "auth"},
	{Pattern: `Kanidm`, Service: "Kanidm", Version: "", Category: "auth"},
	{Pattern: `OpenLDAP`, Service: "OpenLDAP", Version: "", Category: "auth"},
	{Pattern: `Active Directory`, Service: "Active Directory LDAP", Version: "", Category: "auth"},
	{Pattern: `FreeIPA`, Service: "FreeIPA", Version: "", Category: "auth"},
	{Pattern: `Samba`, Service: "Samba AD", Version: "", Category: "auth"},
	{Pattern: `389 Directory`, Service: "389 Directory Server", Version: "", Category: "auth"},
	{Pattern: `OpenDJ`, Service: "OpenDJ", Version: "", Category: "auth"},
	{Pattern: `Gluu`, Service: "Gluu Server", Version: "", Category: "auth"},
	{Pattern: `WSO2`, Service: "WSO2 Identity Server", Version: "", Category: "auth"},
	{Pattern: `PingFederate`, Service: "PingFederate", Version: "", Category: "auth"},
	{Pattern: `ForgeRock`, Service: "ForgeRock AM", Version: "", Category: "auth"},
	{Pattern: `Dex OIDC`, Service: "Dex IdP", Version: "", Category: "auth"},
	{Pattern: `LDAP service`, Service: "LDAP", Version: "", Category: "auth"},

	{Pattern: `Modbus`, Service: "Modbus/TCP", Version: "", Category: "scada"},
	{Pattern: `DNP3`, Service: "DNP3", Version: "", Category: "scada"},
	{Pattern: `EtherNet/IP`, Service: "EtherNet/IP CIP", Version: "", Category: "scada"},
	{Pattern: `PROFINET`, Service: "PROFINET", Version: "", Category: "scada"},
	{Pattern: `BACnet`, Service: "BACnet", Version: "", Category: "scada"},
	{Pattern: `IEC 61850`, Service: "IEC 61850", Version: "", Category: "scada"},
	{Pattern: `OPC UA`, Service: "OPC UA", Version: "", Category: "scada"},
	{Pattern: `Siemens S7`, Service: "Siemens S7", Version: "", Category: "scada"},
	{Pattern: `Modicon`, Service: "Schneider Modicon", Version: "", Category: "scada"},
	{Pattern: `Allen-Bradley`, Service: "Allen-Bradley EtherNet", Version: "", Category: "scada"},
	{Pattern: `GE SRTP`, Service: "GE SRTP", Version: "", Category: "scada"},
	{Pattern: `MELSEC`, Service: "Mitsubishi MELSEC", Version: "", Category: "scada"},
	{Pattern: `OMRON FINS`, Service: "Omron FINS", Version: "", Category: "scada"},
	{Pattern: `Yokogawa`, Service: "Yokogawa", Version: "", Category: "scada"},
	{Pattern: `Honeywell Experion`, Service: "Honeywell Experion", Version: "", Category: "scada"},

	{Pattern: `Hikvision`, Service: "Hikvision Camera", Version: "", Category: "iot"},
	{Pattern: `Dahua`, Service: "Dahua Camera", Version: "", Category: "iot"},
	{Pattern: `AXIS`, Service: "Axis Camera", Version: "", Category: "iot"},
	{Pattern: `Pelco`, Service: "Pelco Camera", Version: "", Category: "iot"},
	{Pattern: `Bosch Security`, Service: "Bosch Camera", Version: "", Category: "iot"},
	{Pattern: `Sony Camera`, Service: "Sony Camera", Version: "", Category: "iot"},
	{Pattern: `Hanwha`, Service: "Hanwha Camera", Version: "", Category: "iot"},
	{Pattern: `Genetec`, Service: "Genetec", Version: "", Category: "iot"},
	{Pattern: `Milestone`, Service: "Milestone XProtect", Version: "", Category: "iot"},
	{Pattern: `ZoneMinder`, Service: "ZoneMinder", Version: "", Category: "iot"},
	{Pattern: `Frigate`, Service: "Frigate NVR", Version: "", Category: "iot"},
	{Pattern: `Home Assistant`, Service: "Home Assistant", Version: "", Category: "iot"},
	{Pattern: `openHAB`, Service: "openHAB", Version: "", Category: "iot"},
	{Pattern: `Domoticz`, Service: "Domoticz", Version: "", Category: "iot"},
	{Pattern: `Homebridge`, Service: "HomeBridge", Version: "", Category: "iot"},
	{Pattern: `Node-RED`, Service: "Node-RED", Version: "", Category: "iot"},
	{Pattern: `ESPHome`, Service: "ESPHome", Version: "", Category: "iot"},
	{Pattern: `Tuya`, Service: "Tuya IoT", Version: "", Category: "iot"},
	{Pattern: `Shelly`, Service: "Shelly Device", Version: "", Category: "iot"},
	{Pattern: `Tapo`, Service: "TP-Link Tapo", Version: "", Category: "iot"},

	{Pattern: `MinIO`, Service: "MinIO", Version: "", Category: "storage"},
	{Pattern: `Ceph`, Service: "Ceph", Version: "", Category: "storage"},
	{Pattern: `GlusterFS`, Service: "GlusterFS", Version: "", Category: "storage"},
	{Pattern: `iSCSI`, Service: "iSCSI target", Version: "", Category: "storage"},
	{Pattern: `FreeNAS`, Service: "FreeNAS", Version: "", Category: "storage"},
	{Pattern: `TrueNAS`, Service: "TrueNAS", Version: "", Category: "storage"},
	{Pattern: `Synology DiskStation`, Service: "Synology DSM", Version: "", Category: "storage"},
	{Pattern: `QNAP`, Service: "QNAP QTS", Version: "", Category: "storage"},
	{Pattern: `ReadyNAS`, Service: "Netgear ReadyNAS", Version: "", Category: "storage"},
	{Pattern: `My Cloud`, Service: "Western Digital MyCloud", Version: "", Category: "storage"},
	{Pattern: `Seagate NAS`, Service: "Seagate NAS", Version: "", Category: "storage"},
	{Pattern: `Buffalo LinkStation`, Service: "Buffalo LinkStation", Version: "", Category: "storage"},
	{Pattern: `Zyxel NAS`, Service: "Zyxel NAS", Version: "", Category: "storage"},
	{Pattern: `Veeam`, Service: "Veeam", Version: "", Category: "storage"},
	{Pattern: `Backup Exec`, Service: "Backup Exec", Version: "", Category: "storage"},
	{Pattern: `Acronis`, Service: "Acronis", Version: "", Category: "storage"},
	{Pattern: `Commvault`, Service: "Commvault", Version: "", Category: "storage"},
	{Pattern: `Bacula`, Service: "Bacula", Version: "", Category: "storage"},
	{Pattern: `Amanda`, Service: "Amanda Backup", Version: "", Category: "storage"},
	{Pattern: `S3 compatible`, Service: "S3 Compatible Storage", Version: "", Category: "storage"},

	{Pattern: `Minecraft`, Service: "Minecraft Server", Version: "", Category: "game"},
	{Pattern: `MOTD`, Service: "Minecraft Java Server", Version: "", Category: "game"},
	{Pattern: `Valve Steam`, Service: "Valve Steam", Version: "", Category: "game"},
	{Pattern: `Source Engine`, Service: "Source Engine", Version: "", Category: "game"},
	{Pattern: `Quake3Arena`, Service: "Quake 3 Arena", Version: "", Category: "game"},
	{Pattern: `Quake Live`, Service: "Quake Live", Version: "", Category: "game"},
	{Pattern: `Unreal Engine`, Service: "Unreal Engine", Version: "", Category: "game"},
	{Pattern: `TS3 ServerQuery`, Service: "TeamSpeak 3", Version: "", Category: "game"},
	{Pattern: `Mumble`, Service: "Mumble", Version: "", Category: "game"},
	{Pattern: `TeamSpeak`, Service: "TeamSpeak", Version: "", Category: "game"},
	{Pattern: `GameSpy`, Service: "GameSpy", Version: "", Category: "game"},
	{Pattern: `RCON`, Service: "RCON", Version: "", Category: "game"},
	{Pattern: `srcds`, Service: "Source Engine Dedicated", Version: "", Category: "game"},
	{Pattern: `half-life`, Service: "Half-Life Server", Version: "", Category: "game"},
	{Pattern: `counterstrike`, Service: "Counter-Strike Server", Version: "", Category: "game"},

	{Pattern: `OpenVPN`, Service: "OpenVPN", Version: "", Category: "vpn"},
	{Pattern: `WireGuard`, Service: "WireGuard", Version: "", Category: "vpn"},
	{Pattern: `StrongSwan`, Service: "StrongSwan IKEv2", Version: "", Category: "vpn"},
	{Pattern: `OpenConnect`, Service: "OpenConnect VPN", Version: "", Category: "vpn"},
	{Pattern: `AnyConnect`, Service: "Cisco AnyConnect", Version: "", Category: "vpn"},
	{Pattern: `Cisco SSL VPN`, Service: "Cisco SSL VPN", Version: "", Category: "vpn"},
	{Pattern: `Pulse Secure`, Service: "Pulse Secure SSL", Version: "", Category: "vpn"},
	{Pattern: `GlobalProtect`, Service: "Palo Alto GlobalProtect", Version: "", Category: "vpn"},
	{Pattern: `Fortinet SSL`, Service: "Fortinet SSL VPN", Version: "", Category: "vpn"},
	{Pattern: `SonicWall SSL`, Service: "SonicWall SSL VPN", Version: "", Category: "vpn"},
	{Pattern: `Check Point Mobile`, Service: "Check Point Mobile Access", Version: "", Category: "vpn"},
	{Pattern: `Array Networks`, Service: "Array Networks SSL VPN", Version: "", Category: "vpn"},
	{Pattern: `BIG-IP`, Service: "F5 BIG-IP SSL", Version: "", Category: "vpn"},
	{Pattern: `Citrix Gateway`, Service: "Citrix Gateway", Version: "", Category: "vpn"},
	{Pattern: `Barracuda SSL VPN`, Service: "Barracuda SSL VPN", Version: "", Category: "vpn"},

	{Pattern: `Pulse Connect`, Service: "Pulse Connect Secure", Version: "", Category: "vpn"},
	{Pattern: `SonicWall SMA`, Service: "SonicWall SMA", Version: "", Category: "vpn"},
	{Pattern: `F5 BIG-IP Access`, Service: "F5 BIG-IP APM", Version: "", Category: "vpn"},
	{Pattern: `Ivanti Connect`, Service: "Ivanti Connect Secure", Version: "", Category: "vpn"},
	{Pattern: `Ivanti Pulse`, Service: "Ivanti Pulse Secure", Version: "", Category: "vpn"},
	{Pattern: `Sangfor SSL VPN`, Service: "Sangfor SSL VPN", Version: "", Category: "vpn"},
	{Pattern: `ZScaler`, Service: "Zscaler Internet Access", Version: "", Category: "vpn"},
	{Pattern: `Tailscale`, Service: "Tailscale", Version: "", Category: "vpn"},
	{Pattern: `ZeroTier`, Service: "ZeroTier", Version: "", Category: "vpn"},
	{Pattern: `Headscale`, Service: "Headscale", Version: "", Category: "vpn"},
	{Pattern: `Pritunl`, Service: "Pritunl VPN", Version: "", Category: "vpn"},
	{Pattern: `Shadowsocks`, Service: "Shadowsocks proxy", Version: "", Category: "vpn"},
	{Pattern: `V2Ray`, Service: "V2Ray proxy", Version: "", Category: "vpn"},
	{Pattern: `Trojan`, Service: "Trojan proxy", Version: "", Category: "vpn"},
	{Pattern: `Netmaker`, Service: "Netmaker WireGuard", Version: "", Category: "vpn"},

	{Pattern: `Server:\s*Starlette`, Service: "Starlette", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Koa`, Service: "Koa.js", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Hapi`, Service: "Hapi.js", Version: "", Category: "http"},
	{Pattern: `Server:\s*istio-envoy`, Service: "Istio (Envoy)", Version: "", Category: "http"},
	{Pattern: `Server:\s*Kong/([\d.]+)`, Service: "Kong Gateway", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*APISIX`, Service: "Apache APISIX", Version: "", Category: "http"},
	{Pattern: `X-AspNet-Version:\s*([\d.]+)`, Service: "ASP.NET", Version: "extract", Category: "http"},
	{Pattern: `X-AspNetMvc-Version:\s*([\d.]+)`, Service: "ASP.NET MVC", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Puma/([\d.]+)`, Service: "Puma (Ruby)", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*thin/([\d.]+)`, Service: "Thin (Ruby)", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Boa/([\d.]+)`, Service: "Boa HTTP", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Mongoose/([\d.]+)`, Service: "Mongoose Embedded", Version: "extract", Category: "http"},
	{Pattern: `X-Powered-By:\s*Django`, Service: "Django", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Flask`, Service: "Flask", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Spring`, Service: "Spring Boot", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Laravel`, Service: "Laravel", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Symfony`, Service: "Symfony", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*CodeIgniter`, Service: "CodeIgniter", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*CakePHP`, Service: "CakePHP", Version: "", Category: "http"},
	{Pattern: `Server:\s*Fastify/([\d.]+)`, Service: "Fastify", Version: "extract", Category: "http"},
	{Pattern: `X-Powered-By:\s*NestJS`, Service: "NestJS", Version: "", Category: "http"},
	{Pattern: `Server:\s*Phoenix`, Service: "Phoenix (Elixir)", Version: "", Category: "http"},
	{Pattern: `Server:\s*Sinatra/([\d.]+)`, Service: "Sinatra (Ruby)", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Ratpack/([\d.]+)`, Service: "Ratpack (Groovy)", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*Play Framework`, Service: "Play Framework", Version: "", Category: "http"},
	{Pattern: `Server:\s*Vert\.x`, Service: "Vert.x (Java)", Version: "", Category: "http"},
	{Pattern: `Server:\s*Dropwizard/([\d.]+)`, Service: "Dropwizard", Version: "extract", Category: "http"},
	{Pattern: `Server:\s*Caddyserver`, Service: "Caddy", Version: "", Category: "http"},
	{Pattern: `X-Forwarded-By:\s*Varnish`, Service: "Varnish Cache", Version: "", Category: "http"},
	{Pattern: `Via:.*Squid`, Service: "Squid Proxy", Version: "", Category: "http"},
	{Pattern: `X-HAProxy-`, Service: "HAProxy", Version: "", Category: "http"},
	{Pattern: `X-Litespeed-Cache`, Service: "LiteSpeed Cache", Version: "", Category: "http"},
	{Pattern: `Server:\s*LiteSpeed`, Service: "LiteSpeed Web Server", Version: "", Category: "http"},
	{Pattern: `NGINX Ingress`, Service: "NGINX Ingress Controller", Version: "", Category: "http"},
	{Pattern: `X-Powered-By:\s*ARR`, Service: "Microsoft ARR", Version: "", Category: "http"},

	{Pattern: `InfluxDB/([\d.]+)`, Service: "InfluxDB", Version: "extract", Category: "database"},
	{Pattern: `X-Influxdb-Version:\s*([\d.]+)`, Service: "InfluxDB", Version: "extract", Category: "database"},
	{Pattern: `CouchDB/([\d.]+)`, Service: "Apache CouchDB", Version: "extract", Category: "database"},
	{Pattern: `CockroachDB\s*v([\d.]+)`, Service: "CockroachDB", Version: "extract", Category: "database"},
	{Pattern: `ArangoDB\s*([\d.]+)`, Service: "ArangoDB", Version: "extract", Category: "database"},
	{Pattern: `ClickHouse/([\d.]+)`, Service: "ClickHouse", Version: "extract", Category: "database"},
	{Pattern: `Apache Hive`, Service: "Apache Hive", Version: "", Category: "database"},
	{Pattern: `Apache Impala`, Service: "Apache Impala", Version: "", Category: "database"},
	{Pattern: `Presto`, Service: "Presto", Version: "", Category: "database"},
	{Pattern: `Trino`, Service: "Trino", Version: "", Category: "database"},
	{Pattern: `Apache Spark`, Service: "Apache Spark", Version: "", Category: "database"},
	{Pattern: `Supabase`, Service: "Supabase", Version: "", Category: "database"},
	{Pattern: `Neon PostgreSQL`, Service: "Neon Serverless PG", Version: "", Category: "database"},
	{Pattern: `SQLite`, Service: "SQLite", Version: "", Category: "database"},
	{Pattern: `Firebird/([\d.]+)`, Service: "Firebird SQL", Version: "extract", Category: "database"},
	{Pattern: `Interbase/([\d.]+)`, Service: "Embarcadero InterBase", Version: "extract", Category: "database"},
	{Pattern: `DB2 SQL`, Service: "IBM Db2", Version: "", Category: "database"},
	{Pattern: `SYBASE`, Service: "Sybase ASE", Version: "", Category: "database"},
	{Pattern: `Adaptive Server Enterprise`, Service: "SAP ASE (Sybase)", Version: "", Category: "database"},
	{Pattern: `SAP HANA`, Service: "SAP HANA", Version: "", Category: "database"},
	{Pattern: `Teradata`, Service: "Teradata", Version: "", Category: "database"},
	{Pattern: `Greenplum`, Service: "Greenplum", Version: "", Category: "database"},
	{Pattern: `SingleStore`, Service: "SingleStore (MemSQL)", Version: "", Category: "database"},
	{Pattern: `Galera Cluster`, Service: "Galera Cluster (MySQL)", Version: "", Category: "database"},
	{Pattern: `etcd`, Service: "etcd (CNCF)", Version: "", Category: "database"},
	{Pattern: `Vitess`, Service: "Vitess (MySQL proxy)", Version: "", Category: "database"},
	{Pattern: `Aerospike`, Service: "Aerospike", Version: "", Category: "database"},
	{Pattern: `Tarantool`, Service: "Tarantool", Version: "", Category: "database"},
	{Pattern: `KeyDB`, Service: "KeyDB (Redis fork)", Version: "", Category: "database"},
	{Pattern: `Meilisearch`, Service: "Meilisearch", Version: "", Category: "database"},
	{Pattern: `Typesense`, Service: "Typesense", Version: "", Category: "database"},
	{Pattern: `Weaviate`, Service: "Weaviate", Version: "", Category: "database"},
	{Pattern: `Qdrant`, Service: "Qdrant", Version: "", Category: "database"},
	{Pattern: `Milvus`, Service: "Milvus", Version: "", Category: "database"},
	{Pattern: `Chroma`, Service: "Chroma (vector DB)", Version: "", Category: "database"},
	{Pattern: `Apache Solr`, Service: "Apache Solr", Version: "", Category: "database"},
	{Pattern: `SolrCloud`, Service: "SolrCloud", Version: "", Category: "database"},
	{Pattern: `EventStoreDB`, Service: "EventStoreDB", Version: "", Category: "database"},
	{Pattern: `SurrealDB`, Service: "SurrealDB", Version: "", Category: "database"},
	{Pattern: `CrateDB`, Service: "CrateDB", Version: "", Category: "database"},
	{Pattern: `FoundationDB`, Service: "FoundationDB", Version: "", Category: "database"},
	{Pattern: `Apache Phoenix`, Service: "Apache Phoenix (HBase SQL)", Version: "", Category: "database"},
	{Pattern: `Apache Kylin`, Service: "Apache Kylin", Version: "", Category: "database"},
	{Pattern: `GridDB`, Service: "GridDB", Version: "", Category: "database"},

	{Pattern: `Ghost/([\d.]+)`, Service: "Ghost CMS", Version: "extract", Category: "cms"},
	{Pattern: `OctoberCMS`, Service: "October CMS", Version: "", Category: "cms"},
	{Pattern: `Kentico`, Service: "Kentico CMS", Version: "", Category: "cms"},
	{Pattern: `DotNetNuke`, Service: "DNN Platform", Version: "", Category: "cms"},
	{Pattern: `Sitefinity`, Service: "Progress Sitefinity", Version: "", Category: "cms"},
	{Pattern: `Episerver`, Service: "Optimizely (Episerver)", Version: "", Category: "cms"},
	{Pattern: `XenForo`, Service: "XenForo Forum", Version: "", Category: "cms"},
	{Pattern: `phpBB`, Service: "phpBB Forum", Version: "", Category: "cms"},
	{Pattern: `vBulletin`, Service: "vBulletin", Version: "", Category: "cms"},
	{Pattern: `MyBB`, Service: "MyBB Forum", Version: "", Category: "cms"},
	{Pattern: `Discourse`, Service: "Discourse Forum", Version: "", Category: "cms"},
	{Pattern: `Flarum`, Service: "Flarum Forum", Version: "", Category: "cms"},
	{Pattern: `Moodle`, Service: "Moodle LMS", Version: "", Category: "cms"},
	{Pattern: `Canvas LMS`, Service: "Canvas LMS", Version: "", Category: "cms"},
	{Pattern: `Blackboard`, Service: "Blackboard LMS", Version: "", Category: "cms"},
	{Pattern: `BigCommerce`, Service: "BigCommerce", Version: "", Category: "cms"},
	{Pattern: `Webflow`, Service: "Webflow", Version: "", Category: "cms"},
	{Pattern: `Contentful`, Service: "Contentful CMS", Version: "", Category: "cms"},
	{Pattern: `Joomla! ([\d.]+)`, Service: "Joomla", Version: "extract", Category: "cms"},
	{Pattern: `Magento/([\d.]+)`, Service: "Magento", Version: "extract", Category: "cms"},
	{Pattern: `BookStack`, Service: "BookStack Wiki", Version: "", Category: "cms"},
	{Pattern: `DokuWiki`, Service: "DokuWiki", Version: "", Category: "cms"},
	{Pattern: `MediaWiki`, Service: "MediaWiki", Version: "", Category: "cms"},
	{Pattern: `TikiWiki`, Service: "TikiWiki", Version: "", Category: "cms"},
	{Pattern: `PmWiki`, Service: "PmWiki", Version: "", Category: "cms"},
	{Pattern: `Anchor CMS`, Service: "Anchor CMS", Version: "", Category: "cms"},
	{Pattern: `FlatPress`, Service: "FlatPress", Version: "", Category: "cms"},
	{Pattern: `Textpattern`, Service: "Textpattern CMS", Version: "", Category: "cms"},
	{Pattern: `b2evolution`, Service: "b2evolution", Version: "", Category: "cms"},
	{Pattern: `MODx`, Service: "MODX Revolution", Version: "", Category: "cms"},

	{Pattern: `Poshc2`, Service: "PoshC2", Version: "", Category: "security"},
	{Pattern: `Acunetix`, Service: "Acunetix Scanner", Version: "", Category: "security"},
	{Pattern: `Invicti`, Service: "Invicti Scanner", Version: "", Category: "security"},
	{Pattern: `Veracode`, Service: "Veracode DAST", Version: "", Category: "security"},
	{Pattern: `PortSwigger`, Service: "PortSwigger (Burp)", Version: "", Category: "security"},
	{Pattern: `Snyk`, Service: "Snyk Security", Version: "", Category: "security"},
	{Pattern: `SonarQube`, Service: "SonarQube", Version: "", Category: "security"},
	{Pattern: `Wazuh`, Service: "Wazuh SIEM", Version: "", Category: "security"},
	{Pattern: `OSSEC`, Service: "OSSEC HIDS", Version: "", Category: "security"},
	{Pattern: `Suricata`, Service: "Suricata IDS/IPS", Version: "", Category: "security"},
	{Pattern: `Snort/([\d.]+)`, Service: "Snort IDS", Version: "extract", Category: "security"},
	{Pattern: `Zeek`, Service: "Zeek Network Monitor", Version: "", Category: "security"},
	{Pattern: `Falco`, Service: "Falco runtime security", Version: "", Category: "security"},
	{Pattern: `Trivy`, Service: "Trivy Scanner", Version: "", Category: "security"},
	{Pattern: `Anchore`, Service: "Anchore Engine", Version: "", Category: "security"},
	{Pattern: `Aqua Security`, Service: "Aqua Security", Version: "", Category: "security"},
	{Pattern: `Sysdig`, Service: "Sysdig", Version: "", Category: "security"},
	{Pattern: `CrowdSec`, Service: "CrowdSec", Version: "", Category: "security"},
	{Pattern: `ModSecurity`, Service: "ModSecurity WAF", Version: "", Category: "security"},

	{Pattern: `X-Jenkins:\s*([\d.]+)`, Service: "Jenkins", Version: "extract", Category: "cicd"},
	{Pattern: `GitLab/([\d.]+)`, Service: "GitLab", Version: "extract", Category: "cicd"},
	{Pattern: `Gitea/([\d.]+)`, Service: "Gitea", Version: "extract", Category: "cicd"},
	{Pattern: `Gogs/([\d.]+)`, Service: "Gogs", Version: "extract", Category: "cicd"},
	{Pattern: `GogsServer`, Service: "Gogs Git", Version: "", Category: "cicd"},
	{Pattern: `Gerrit Code Review`, Service: "Gerrit", Version: "", Category: "cicd"},
	{Pattern: `Phabricator`, Service: "Phabricator", Version: "", Category: "cicd"},
	{Pattern: `Crucible`, Service: "Atlassian Crucible", Version: "", Category: "cicd"},
	{Pattern: `Rhodecode`, Service: "RhodeCode", Version: "", Category: "cicd"},
	{Pattern: `Kallithea`, Service: "Kallithea", Version: "", Category: "cicd"},
	{Pattern: `Allure`, Service: "Allure TestOps", Version: "", Category: "cicd"},
	{Pattern: `SonarQube/([\d.]+)`, Service: "SonarQube", Version: "extract", Category: "cicd"},
	{Pattern: `GitHub Enterprise`, Service: "GitHub Enterprise Server", Version: "", Category: "cicd"},
	{Pattern: `Bitbucket Server`, Service: "Bitbucket Server", Version: "", Category: "cicd"},
	{Pattern: `Azure Repos`, Service: "Azure Repos", Version: "", Category: "cicd"},
	{Pattern: `Buildkite`, Service: "Buildkite", Version: "", Category: "cicd"},
	{Pattern: `Semaphore CI`, Service: "Semaphore CI", Version: "", Category: "cicd"},
	{Pattern: `Codefresh`, Service: "Codefresh", Version: "", Category: "cicd"},
	{Pattern: `Buddy CI`, Service: "Buddy CI", Version: "", Category: "cicd"},

	{Pattern: `Server:\s*AkamaiGHost`, Service: "Akamai CDN", Version: "", Category: "cdn"},
	{Pattern: `Server:\s*cloudflare`, Service: "Cloudflare", Version: "", Category: "cdn"},
	{Pattern: `Server:\s*Fastly`, Service: "Fastly CDN", Version: "", Category: "cdn"},
	{Pattern: `X-Cache:.*cloudfront`, Service: "AWS CloudFront", Version: "", Category: "cdn"},
	{Pattern: `Server:\s*awselb`, Service: "AWS ELB", Version: "", Category: "cdn"},
	{Pattern: `Server:\s*AmazonS3`, Service: "Amazon S3", Version: "", Category: "cdn"},
	{Pattern: `X-Amz-Cf-Id:`, Service: "AWS CloudFront", Version: "", Category: "cdn"},
	{Pattern: `X-Cdn:\s*KeyCDN`, Service: "KeyCDN", Version: "", Category: "cdn"},
	{Pattern: `Server:\s*BunnyCDN`, Service: "BunnyCDN", Version: "", Category: "cdn"},

	{Pattern: `Server:\s*Sucuri`, Service: "Sucuri WAF", Version: "", Category: "waf"},
	{Pattern: `Server:\s*F5 BIG-IP`, Service: "F5 BIG-IP LTM", Version: "", Category: "waf"},
	{Pattern: `X-Cdn:\s*Imperva`, Service: "Imperva WAF", Version: "", Category: "waf"},
	{Pattern: `X-Iinfo:`, Service: "Incapsula WAF", Version: "", Category: "waf"},
	{Pattern: `X-Sucuri-ID:`, Service: "Sucuri WAF", Version: "", Category: "waf"},
	{Pattern: `X-Powered-By:\s*AWS WAF`, Service: "AWS WAF", Version: "", Category: "waf"},

	{Pattern: `NS1`, Service: "NS1 DNS", Version: "", Category: "dns"},
	{Pattern: `PowerDNS`, Service: "PowerDNS", Version: "", Category: "dns"},
	{Pattern: `Unbound ([\d.]+)`, Service: "Unbound DNS", Version: "extract", Category: "dns"},
	{Pattern: `BIND ([\d.]+)`, Service: "ISC BIND", Version: "extract", Category: "dns"},
	{Pattern: `dnsmasq-([\d.]+)`, Service: "dnsmasq", Version: "extract", Category: "dns"},
	{Pattern: `CoreDNS`, Service: "CoreDNS (k8s)", Version: "", Category: "dns"},
	{Pattern: `Knot DNS`, Service: "Knot DNS", Version: "", Category: "dns"},
	{Pattern: `NSD`, Service: "NSD Authoritative DNS", Version: "", Category: "dns"},
	{Pattern: `Technitium DNS`, Service: "Technitium DNS Server", Version: "", Category: "dns"},
	{Pattern: `AdGuard Home`, Service: "AdGuard Home DNS", Version: "", Category: "dns"},
	{Pattern: `Pi-hole`, Service: "Pi-hole DNS", Version: "", Category: "dns"},

	{Pattern: `X-Amz-Request-Id:`, Service: "Amazon AWS", Version: "", Category: "cloud"},
	{Pattern: `X-Google-Backends:`, Service: "Google Cloud", Version: "", Category: "cloud"},
	{Pattern: `X-Azure-Ref:`, Service: "Microsoft Azure", Version: "", Category: "cloud"},
	{Pattern: `X-Ms-Request-Id:`, Service: "Microsoft Azure", Version: "", Category: "cloud"},
	{Pattern: `X-Oracle-Dms-Ecid:`, Service: "Oracle Cloud", Version: "", Category: "cloud"},
	{Pattern: `X-Alibaba-`, Service: "Alibaba Cloud", Version: "", Category: "cloud"},
	{Pattern: `X-Tencent-`, Service: "Tencent Cloud", Version: "", Category: "cloud"},
	{Pattern: `X-Heroku-App-Default-Domain`, Service: "Heroku", Version: "", Category: "cloud"},
	{Pattern: `Fly\.io`, Service: "Fly.io", Version: "", Category: "cloud"},
	{Pattern: `Render`, Service: "Render.com", Version: "", Category: "cloud"},
	{Pattern: `Railway`, Service: "Railway", Version: "", Category: "cloud"},
	{Pattern: `Vercel`, Service: "Vercel", Version: "", Category: "cloud"},
	{Pattern: `X-Vercel-Id:`, Service: "Vercel", Version: "", Category: "cloud"},
	{Pattern: `Netlify`, Service: "Netlify", Version: "", Category: "cloud"},
	{Pattern: `X-Nf-Request-Id:`, Service: "Netlify", Version: "", Category: "cloud"},
	{Pattern: `Firebase`, Service: "Google Firebase", Version: "", Category: "cloud"},
	{Pattern: `X-Firebase-`, Service: "Google Firebase", Version: "", Category: "cloud"},
	{Pattern: `PocketBase`, Service: "PocketBase", Version: "", Category: "cloud"},
	{Pattern: `Appwrite`, Service: "Appwrite", Version: "", Category: "cloud"},
	{Pattern: `Back4App`, Service: "Back4App", Version: "", Category: "cloud"},
	{Pattern: `Parse Server`, Service: "Parse Server", Version: "", Category: "cloud"},
	{Pattern: `Nhost`, Service: "Nhost", Version: "", Category: "cloud"},
	{Pattern: `Hasura`, Service: "Hasura GraphQL", Version: "", Category: "cloud"},
	{Pattern: `Linode`, Service: "Linode (Akamai Cloud)", Version: "", Category: "cloud"},
	{Pattern: `DigitalOcean`, Service: "DigitalOcean", Version: "", Category: "cloud"},
	{Pattern: `Hetzner`, Service: "Hetzner Cloud", Version: "", Category: "cloud"},
	{Pattern: `Vultr`, Service: "Vultr", Version: "", Category: "cloud"},
	{Pattern: `OVH`, Service: "OVH Cloud", Version: "", Category: "cloud"},
	{Pattern: `Scaleway`, Service: "Scaleway", Version: "", Category: "cloud"},
	{Pattern: `Exoscale`, Service: "Exoscale", Version: "", Category: "cloud"},
	{Pattern: `Cloudinary`, Service: "Cloudinary", Version: "", Category: "cloud"},
	{Pattern: `imgix`, Service: "imgix CDN", Version: "", Category: "cloud"},

	{Pattern: `Mattermost`, Service: "Mattermost", Version: "", Category: "collab"},
	{Pattern: `Rocket\.Chat`, Service: "Rocket.Chat", Version: "", Category: "collab"},
	{Pattern: `Matrix Synapse`, Service: "Matrix Synapse", Version: "", Category: "collab"},
	{Pattern: `Element`, Service: "Element (Matrix client)", Version: "", Category: "collab"},
	{Pattern: `Zulip`, Service: "Zulip Chat", Version: "", Category: "collab"},
	{Pattern: `Nextcloud`, Service: "Nextcloud", Version: "", Category: "collab"},
	{Pattern: `ownCloud`, Service: "ownCloud", Version: "", Category: "collab"},
	{Pattern: `Seafile`, Service: "Seafile", Version: "", Category: "collab"},
	{Pattern: `OnlyOffice`, Service: "ONLYOFFICE", Version: "", Category: "collab"},
	{Pattern: `Collabora`, Service: "Collabora Online", Version: "", Category: "collab"},
	{Pattern: `Jitsi`, Service: "Jitsi Meet", Version: "", Category: "collab"},
	{Pattern: `BigBlueButton`, Service: "BigBlueButton", Version: "", Category: "collab"},
	{Pattern: `Etherpad`, Service: "Etherpad", Version: "", Category: "collab"},
	{Pattern: `HedgeDoc`, Service: "HedgeDoc", Version: "", Category: "collab"},
	{Pattern: `Gitbook`, Service: "GitBook", Version: "", Category: "collab"},
	{Pattern: `Outline`, Service: "Outline Wiki", Version: "", Category: "collab"},
	{Pattern: `WikiJS`, Service: "Wiki.js", Version: "", Category: "collab"},
	{Pattern: `Confluence`, Service: "Atlassian Confluence", Version: "", Category: "collab"},
	{Pattern: `Jira Software`, Service: "Atlassian Jira", Version: "", Category: "collab"},
	{Pattern: `Bitbucket`, Service: "Atlassian Bitbucket", Version: "", Category: "collab"},
	{Pattern: `Redmine`, Service: "Redmine", Version: "", Category: "collab"},
	{Pattern: `MantisBT`, Service: "MantisBT", Version: "", Category: "collab"},
	{Pattern: `Trac`, Service: "Trac", Version: "", Category: "collab"},
	{Pattern: `YouTrack`, Service: "JetBrains YouTrack", Version: "", Category: "collab"},
	{Pattern: `Taiga`, Service: "Taiga", Version: "", Category: "collab"},
	{Pattern: `Wekan`, Service: "Wekan Kanban", Version: "", Category: "collab"},
	{Pattern: `Focalboard`, Service: "Focalboard (Mattermost)", Version: "", Category: "collab"},
	{Pattern: `Leantime`, Service: "Leantime", Version: "", Category: "collab"},
	{Pattern: `Linear`, Service: "Linear", Version: "", Category: "collab"},
	{Pattern: `Plane`, Service: "Plane", Version: "", Category: "collab"},
	{Pattern: `Notea`, Service: "Notea", Version: "", Category: "collab"},
	{Pattern: `AppFlowy`, Service: "AppFlowy", Version: "", Category: "collab"},
	{Pattern: `Affine`, Service: "AFFiNE", Version: "", Category: "collab"},

	{Pattern: `x-minio-deployment-id:`, Service: "MinIO", Version: "", Category: "storage"},
	{Pattern: `Restic`, Service: "Restic Backup", Version: "", Category: "storage"},
	{Pattern: `Borg`, Service: "BorgBackup", Version: "", Category: "storage"},
	{Pattern: `Duplicati`, Service: "Duplicati", Version: "", Category: "storage"},
	{Pattern: `Longhorn`, Service: "Longhorn (k8s storage)", Version: "", Category: "storage"},
	{Pattern: `Rook`, Service: "Rook Ceph Operator", Version: "", Category: "storage"},
	{Pattern: `OpenEBS`, Service: "OpenEBS", Version: "", Category: "storage"},
	{Pattern: `Portworx`, Service: "Portworx", Version: "", Category: "storage"},
	{Pattern: `SeaweedFS`, Service: "SeaweedFS", Version: "", Category: "storage"},
	{Pattern: `JuiceFS`, Service: "JuiceFS", Version: "", Category: "storage"},
	{Pattern: `IPFS`, Service: "IPFS", Version: "", Category: "storage"},
	{Pattern: `Ceph RADOS`, Service: "Ceph RADOS", Version: "", Category: "storage"},
	{Pattern: `NFS daemon`, Service: "NFS Server", Version: "", Category: "storage"},
	{Pattern: `Samba Server`, Service: "Samba SMB", Version: "", Category: "storage"},
	{Pattern: `Rsync daemon`, Service: "rsync daemon", Version: "", Category: "storage"},

	{Pattern: `Shibboleth`, Service: "Shibboleth IdP", Version: "", Category: "auth"},
	{Pattern: `SimpleSAMLphp`, Service: "SimpleSAMLphp", Version: "", Category: "auth"},
	{Pattern: `Kerberos`, Service: "Kerberos KDC", Version: "", Category: "auth"},
	{Pattern: `RADIUS`, Service: "RADIUS Server", Version: "", Category: "auth"},
	{Pattern: `FreeRADIUS`, Service: "FreeRADIUS", Version: "", Category: "auth"},
	{Pattern: `Cisco ISE`, Service: "Cisco ISE", Version: "", Category: "auth"},
	{Pattern: `TACACS`, Service: "TACACS Server", Version: "", Category: "auth"},
	{Pattern: `LDAP`, Service: "LDAP Directory", Version: "", Category: "auth"},
	{Pattern: `Active Directory`, Service: "Active Directory", Version: "", Category: "auth"},

	{Pattern: `X-Docker-Registry-Version:`, Service: "Docker Registry v1", Version: "", Category: "container"},
	{Pattern: `k8s`, Service: "Kubernetes", Version: "", Category: "container"},
	{Pattern: `crio`, Service: "CRI-O", Version: "", Category: "container"},
	{Pattern: `Lens IDE`, Service: "Lens Kubernetes IDE", Version: "", Category: "container"},
	{Pattern: `Octant`, Service: "Octant K8s UI", Version: "", Category: "container"},
	{Pattern: `kube-apiserver`, Service: "Kubernetes API Server", Version: "", Category: "container"},
	{Pattern: `Helm/([\d.]+)`, Service: "Helm", Version: "extract", Category: "container"},
	{Pattern: `Podman`, Service: "Podman", Version: "", Category: "container"},
	{Pattern: `LXC`, Service: "LXC Containers", Version: "", Category: "container"},
	{Pattern: `LXD`, Service: "LXD", Version: "", Category: "container"},
	{Pattern: `Cilium`, Service: "Cilium (eBPF)", Version: "", Category: "container"},
	{Pattern: `Calico`, Service: "Calico CNI", Version: "", Category: "container"},
	{Pattern: `MetalLB`, Service: "MetalLB", Version: "", Category: "container"},
	{Pattern: `Weave Net`, Service: "Weave Net CNI", Version: "", Category: "container"},
	{Pattern: `Kata Containers`, Service: "Kata Containers", Version: "", Category: "container"},
	{Pattern: `gVisor`, Service: "gVisor", Version: "", Category: "container"},
	{Pattern: `Flannel`, Service: "Flannel CNI", Version: "", Category: "container"},
	{Pattern: `Multus`, Service: "Multus CNI", Version: "", Category: "container"},
	{Pattern: `Karpenter`, Service: "Karpenter (AWS)", Version: "", Category: "container"},
	{Pattern: `KEDA`, Service: "KEDA (event-driven autoscaler)", Version: "", Category: "container"},
	{Pattern: `Crossplane`, Service: "Crossplane", Version: "", Category: "container"},
	{Pattern: `Cluster API`, Service: "Cluster API", Version: "", Category: "container"},

	{Pattern: `Proxmox`, Service: "Proxmox VE", Version: "", Category: "virt"},
	{Pattern: `VMware ESXi`, Service: "VMware ESXi", Version: "", Category: "virt"},
	{Pattern: `VMware vCenter`, Service: "VMware vCenter", Version: "", Category: "virt"},
	{Pattern: `VMware vSphere`, Service: "VMware vSphere", Version: "", Category: "virt"},
	{Pattern: `XenServer`, Service: "XenServer", Version: "", Category: "virt"},
	{Pattern: `Xen Hypervisor`, Service: "Xen Hypervisor", Version: "", Category: "virt"},
	{Pattern: `oVirt`, Service: "oVirt", Version: "", Category: "virt"},
	{Pattern: `RHEV`, Service: "Red Hat Virtualization", Version: "", Category: "virt"},
	{Pattern: `OpenStack`, Service: "OpenStack", Version: "", Category: "virt"},
	{Pattern: `KVM`, Service: "KVM", Version: "", Category: "virt"},
	{Pattern: `libvirt`, Service: "libvirt", Version: "", Category: "virt"},
	{Pattern: `VirtualBox`, Service: "VirtualBox", Version: "", Category: "virt"},
	{Pattern: `Nutanix`, Service: "Nutanix AOS", Version: "", Category: "virt"},
	{Pattern: `Hyper-V`, Service: "Microsoft Hyper-V", Version: "", Category: "virt"},
	{Pattern: `QEMU`, Service: "QEMU", Version: "", Category: "virt"},
	{Pattern: `Bhyve`, Service: "Bhyve (FreeBSD)", Version: "", Category: "virt"},
	{Pattern: `VMware Workstation`, Service: "VMware Workstation", Version: "", Category: "virt"},

	{Pattern: `PRTG`, Service: "PRTG Network Monitor", Version: "", Category: "monitoring"},
	{Pattern: `SolarWinds`, Service: "SolarWinds", Version: "", Category: "monitoring"},
	{Pattern: `ManageEngine`, Service: "ManageEngine", Version: "", Category: "monitoring"},
	{Pattern: `Icinga2`, Service: "Icinga2", Version: "", Category: "monitoring"},
	{Pattern: `Icinga/([\d.]+)`, Service: "Icinga", Version: "extract", Category: "monitoring"},
	{Pattern: `Checkmk`, Service: "Checkmk", Version: "", Category: "monitoring"},
	{Pattern: `Sensu`, Service: "Sensu", Version: "", Category: "monitoring"},
	{Pattern: `Telegraf`, Service: "Telegraf", Version: "", Category: "monitoring"},
	{Pattern: `Thanos`, Service: "Thanos", Version: "", Category: "monitoring"},
	{Pattern: `Cortex`, Service: "Cortex (Prometheus)", Version: "", Category: "monitoring"},
	{Pattern: `Mimir`, Service: "Grafana Mimir", Version: "", Category: "monitoring"},
	{Pattern: `node_exporter`, Service: "Prometheus Node Exporter", Version: "", Category: "monitoring"},
	{Pattern: `blackbox_exporter`, Service: "Prometheus Blackbox Exporter", Version: "", Category: "monitoring"},
	{Pattern: `pushgateway`, Service: "Prometheus Pushgateway", Version: "", Category: "monitoring"},
	{Pattern: `Uptime Kuma`, Service: "Uptime Kuma", Version: "", Category: "monitoring"},
	{Pattern: `Better Stack`, Service: "Better Stack Uptime", Version: "", Category: "monitoring"},
	{Pattern: `ntopng`, Service: "ntopng", Version: "", Category: "monitoring"},
	{Pattern: `Elastic APM`, Service: "Elastic APM", Version: "", Category: "monitoring"},
	{Pattern: `Vector`, Service: "Vector (observability)", Version: "", Category: "monitoring"},
	{Pattern: `OpenObserve`, Service: "OpenObserve", Version: "", Category: "monitoring"},
	{Pattern: `Signoz`, Service: "SigNoz", Version: "", Category: "monitoring"},

	{Pattern: `HP Jetdirect`, Service: "HP JetDirect", Version: "", Category: "printer"},
	{Pattern: `HP LaserJet`, Service: "HP LaserJet", Version: "", Category: "printer"},
	{Pattern: `CUPS/([\d.]+)`, Service: "CUPS", Version: "extract", Category: "printer"},
	{Pattern: `IPP/[\d.]+`, Service: "IPP (Internet Printing)", Version: "", Category: "printer"},
	{Pattern: `Lexmark`, Service: "Lexmark Printer", Version: "", Category: "printer"},
	{Pattern: `Brother`, Service: "Brother Printer", Version: "", Category: "printer"},
	{Pattern: `EPSON_Linux`, Service: "Epson Printer", Version: "", Category: "printer"},
	{Pattern: `Xerox_Printer`, Service: "Xerox Printer", Version: "", Category: "printer"},
	{Pattern: `Ricoh Printer`, Service: "Ricoh Printer", Version: "", Category: "printer"},
	{Pattern: `Canon HTTP`, Service: "Canon Printer", Version: "", Category: "printer"},
	{Pattern: `Kyocera Printer`, Service: "Kyocera Printer", Version: "", Category: "printer"},
	{Pattern: `Sharp Printer`, Service: "Sharp Printer", Version: "", Category: "printer"},
	{Pattern: `OKI Printer`, Service: "OKI Printer", Version: "", Category: "printer"},
	{Pattern: `KM_NetPrint`, Service: "Konica Minolta Printer", Version: "", Category: "printer"},
	{Pattern: `FujiXerox`, Service: "Fuji Xerox Printer", Version: "", Category: "printer"},
	{Pattern: `Samsung Printer`, Service: "Samsung Printer", Version: "", Category: "printer"},
	{Pattern: `Dell Printer`, Service: "Dell Printer", Version: "", Category: "printer"},

	{Pattern: `SAP NetWeaver`, Service: "SAP NetWeaver", Version: "", Category: "erp"},
	{Pattern: `SAP BusinessObjects`, Service: "SAP BusinessObjects", Version: "", Category: "erp"},
	{Pattern: `SAP Fiori`, Service: "SAP Fiori", Version: "", Category: "erp"},
	{Pattern: `Oracle E-Business`, Service: "Oracle EBS", Version: "", Category: "erp"},
	{Pattern: `Oracle PeopleSoft`, Service: "Oracle PeopleSoft", Version: "", Category: "erp"},
	{Pattern: `Oracle JD Edwards`, Service: "Oracle JD Edwards", Version: "", Category: "erp"},
	{Pattern: `Microsoft Dynamics`, Service: "Microsoft Dynamics", Version: "", Category: "erp"},
	{Pattern: `Odoo`, Service: "Odoo ERP", Version: "", Category: "erp"},
	{Pattern: `ERPNext`, Service: "ERPNext", Version: "", Category: "erp"},
	{Pattern: `Dolibarr`, Service: "Dolibarr ERP", Version: "", Category: "erp"},
	{Pattern: `NetSuite`, Service: "Oracle NetSuite", Version: "", Category: "erp"},
	{Pattern: `Infor`, Service: "Infor ERP", Version: "", Category: "erp"},
	{Pattern: `Epicor`, Service: "Epicor ERP", Version: "", Category: "erp"},
	{Pattern: `Sage Business`, Service: "Sage Business Cloud", Version: "", Category: "erp"},
	{Pattern: `Acumatica`, Service: "Acumatica", Version: "", Category: "erp"},
	{Pattern: `IFS Applications`, Service: "IFS Applications", Version: "", Category: "erp"},

	{Pattern: `pgAdmin`, Service: "pgAdmin", Version: "", Category: "dbadmin"},
	{Pattern: `phpMyAdmin`, Service: "phpMyAdmin", Version: "", Category: "dbadmin"},
	{Pattern: `Adminer`, Service: "Adminer", Version: "", Category: "dbadmin"},
	{Pattern: `phpPgAdmin`, Service: "phpPgAdmin", Version: "", Category: "dbadmin"},
	{Pattern: `Metabase`, Service: "Metabase", Version: "", Category: "dbadmin"},
	{Pattern: `Redash`, Service: "Redash", Version: "", Category: "dbadmin"},
	{Pattern: `Superset`, Service: "Apache Superset", Version: "", Category: "dbadmin"},
	{Pattern: `DataGrip`, Service: "JetBrains DataGrip", Version: "", Category: "dbadmin"},
	{Pattern: `Beekeeper Studio`, Service: "Beekeeper Studio", Version: "", Category: "dbadmin"},
	{Pattern: `TablePlus`, Service: "TablePlus", Version: "", Category: "dbadmin"},

	{Pattern: `Swagger UI`, Service: "Swagger UI", Version: "", Category: "api"},
	{Pattern: `ReDoc`, Service: "ReDoc API Docs", Version: "", Category: "api"},
	{Pattern: `GraphQL Playground`, Service: "GraphQL Playground", Version: "", Category: "api"},
	{Pattern: `Apollo GraphQL`, Service: "Apollo GraphQL", Version: "", Category: "api"},
	{Pattern: `Hasura GraphQL Engine`, Service: "Hasura GraphQL Engine", Version: "", Category: "api"},
	{Pattern: `Kong Admin`, Service: "Kong Admin API", Version: "", Category: "api"},
	{Pattern: `Tyk API`, Service: "Tyk API Gateway", Version: "", Category: "api"},
	{Pattern: `Apigee`, Service: "Apigee API Gateway", Version: "", Category: "api"},
	{Pattern: `MuleSoft`, Service: "MuleSoft Anypoint", Version: "", Category: "api"},
	{Pattern: `WSO2 API Manager`, Service: "WSO2 API Manager", Version: "", Category: "api"},
	{Pattern: `Ambassador`, Service: "Ambassador API Gateway", Version: "", Category: "api"},
	{Pattern: `KrakenD`, Service: "KrakenD", Version: "", Category: "api"},

	{Pattern: `Zigbee2MQTT`, Service: "Zigbee2MQTT", Version: "", Category: "iot"},
	{Pattern: `Z-Wave JS`, Service: "Z-Wave JS", Version: "", Category: "iot"},
	{Pattern: `Tasmota`, Service: "Tasmota firmware", Version: "", Category: "iot"},
	{Pattern: `WLED`, Service: "WLED", Version: "", Category: "iot"},
	{Pattern: `Reolink`, Service: "Reolink Camera", Version: "", Category: "iot"},
	{Pattern: `Eufy`, Service: "Eufy Camera", Version: "", Category: "iot"},
	{Pattern: `AmcrestView`, Service: "Amcrest Camera", Version: "", Category: "iot"},
	{Pattern: `Foscam`, Service: "Foscam Camera", Version: "", Category: "iot"},
	{Pattern: `Ubiquiti UniFi`, Service: "Ubiquiti UniFi Camera", Version: "", Category: "iot"},
	{Pattern: `Mobotix`, Service: "Mobotix Camera", Version: "", Category: "iot"},
	{Pattern: `Digital Watchdog`, Service: "Digital Watchdog NVR", Version: "", Category: "iot"},
	{Pattern: `Vivotek`, Service: "Vivotek Camera", Version: "", Category: "iot"},
	{Pattern: `Avigilon`, Service: "Avigilon Camera", Version: "", Category: "iot"},
	{Pattern: `Verkada`, Service: "Verkada Camera", Version: "", Category: "iot"},
	{Pattern: `Loxone`, Service: "Loxone Smart Home", Version: "", Category: "iot"},
	{Pattern: `Homey`, Service: "Homey Smart Home", Version: "", Category: "iot"},
	{Pattern: `SmartThings`, Service: "Samsung SmartThings", Version: "", Category: "iot"},
	{Pattern: `eWeLink`, Service: "eWeLink Smart Home", Version: "", Category: "iot"},
	{Pattern: `Sonoff`, Service: "Sonoff", Version: "", Category: "iot"},
	{Pattern: `ioBroker`, Service: "ioBroker", Version: "", Category: "iot"},
	{Pattern: `Gladys Assistant`, Service: "Gladys Assistant", Version: "", Category: "iot"},
	{Pattern: `Jeedom`, Service: "Jeedom", Version: "", Category: "iot"},

	{Pattern: `220.*Haraka`, Service: "Haraka SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*Stalwart`, Service: "Stalwart Mail Server", Version: "", Category: "smtp"},
	{Pattern: `220.*MailCow`, Service: "MailCow", Version: "", Category: "smtp"},
	{Pattern: `220.*Maildrop`, Service: "Maildrop SMTP", Version: "", Category: "smtp"},
	{Pattern: `220.*OpenSMTPD`, Service: "OpenSMTPD", Version: "", Category: "smtp"},
	{Pattern: `220.*Halon`, Service: "Halon MTA", Version: "", Category: "smtp"},
	{Pattern: `220.*SparkPost`, Service: "SparkPost MTA", Version: "", Category: "smtp"},

	{Pattern: `Net-SNMP`, Service: "Net-SNMP", Version: "", Category: "network"},
	{Pattern: `SNMPv2-MIB`, Service: "SNMP MIB-II", Version: "", Category: "network"},
	{Pattern: `Ericsson`, Service: "Ericsson", Version: "", Category: "network"},
	{Pattern: `Nokia SR OS`, Service: "Nokia SR OS", Version: "", Category: "network"},
	{Pattern: `Ciena`, Service: "Ciena", Version: "", Category: "network"},
	{Pattern: `Ribbon Communications`, Service: "Ribbon Communications", Version: "", Category: "network"},
	{Pattern: `AudioCodes`, Service: "AudioCodes", Version: "", Category: "network"},
	{Pattern: `NETCONF`, Service: "NETCONF", Version: "", Category: "network"},
	{Pattern: `gRPC`, Service: "gRPC", Version: "", Category: "network"},
	{Pattern: `RESTCONF`, Service: "RESTCONF", Version: "", Category: "network"},
}

