package output

import (
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/bytezora/recon-x/internal/source"
)

type SourceReport struct {
	Target      string        `json:"target"`
	GeneratedAt string        `json:"generated_at"`
	Source      source.Result `json:"source"`
}

func WriteSourceJSON(path, target string, src source.Result) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	enc := json.NewEncoder(f)
	enc.SetIndent("", "  ")
	return enc.Encode(SourceReport{
		Target:      target,
		GeneratedAt: time.Now().Format(time.RFC3339),
		Source:      src,
	})
}

func WriteSourceMarkdown(path, target string, src source.Result) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	w := func(format string, args ...interface{}) {
		fmt.Fprintf(f, format+"\n", args...)
	}

	w("# recon-x Source Scan: %s", target)
	w("**Generated:** %s", time.Now().Format(time.RFC3339))
	w("")
	w("## Summary")
	w("")
	w("| Metric | Value |")
	w("|--------|------:|")
	w("| Files scanned | %d |", src.Files)
	w("| Manifests | %d |", len(src.Manifests))
	w("| Routes | %d |", len(src.Routes))
	w("| Findings | %d |", len(src.Findings))
	w("")

	if len(src.Findings) > 0 {
		w("## Findings")
		w("")
		w("| Priority | Severity | Type | Fingerprint | Location | Title | Evidence |")
		w("|----------|----------|------|-------------|----------|-------|----------|")
		for _, f := range src.Findings {
			w("| %s | %s | %s | %s | %s | %s | %s |",
				mdCell(f.Priority), mdCell(string(f.Severity)), mdCell(f.Type), mdCell(f.Fingerprint), mdCell(f.AffectedURL), mdCell(f.Title), mdCell(f.Evidence))
		}
		w("")
	}

	if len(src.Manifests) > 0 {
		w("## Dependency Manifests")
		w("")
		w("| Path | Ecosystem | Package | Dependencies Parsed |")
		w("|------|-----------|---------|--------------------:|")
		for _, m := range src.Manifests {
			w("| %s | %s | %s | %d |", mdCell(m.Path), mdCell(m.Ecosystem), mdCell(m.PackageName), len(m.Dependencies))
		}
		w("")
	}

	if len(src.Routes) > 0 {
		w("## Source Routes")
		w("")
		w("| Method | Path | File | Source | Live URL |")
		w("|--------|------|------|--------|----------|")
		for _, r := range src.Routes {
			w("| %s | %s | %s:%d | %s | %s |", mdCell(r.Method), mdCell(r.Path), mdCell(r.File), r.Line, mdCell(r.Source), mdCell(r.LiveURL))
		}
		w("")
	}

	w("---")
	w("*Generated by recon-x — scan only authorized code and targets*")
	return nil
}

func mdCell(s string) string {
	s = strings.ReplaceAll(s, "\r", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "|", `\|`)
	return strings.TrimSpace(s)
}
